### ISSUE TITLE
SQL Connection Error

### ISSUE THREAD

**Issue by channel9network** [Resgrid/Core#1]
Namepipe error when running the SQL script in the install instructions. Running SQL Server 2017 express. No firewall on

Before opening:

- [Search for duplicate or closed issues](https://github.com/Resgrid/Core?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/Resgrid/Core/blob/master/.github/CONTRIBUTING.md)

Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Relevant department settings (i.e. Time Zone) if submitting data or an update to existing data what fields were support and what state they were in
- A reproducible example on our public SaaS system [Resgrid](https://resgrid.com/) please only supply the department code in your bug, **no user names, passwords or department ids**

**Comment by ucswift** [comment]
@channel9network is it when your running the `Resgrid.Console.exe dbupdate` command? Did you install SQL Server Management studio as well? If so are you able to connect to the installed SQL Instance? Assuming you installed it in C:\Resgrid, there should be a file called ResgridConfig.json in C:\Resgrid\Config, a property there called `DataConfig.ConnectionString` will point to the database installation. If the installation is named that default connection string won't work.

**Comment by channel9network** [comment]
Shawn,


Yes I did install it and yes it is when I run the command. What do I make the connection string for localhost\resgrid. We named the instance resgrid. All I see in the config file is (local), but see that in several places.
Jacob Pasley
CEO
Channel 9 Network
P: (502) 316-8060
W: www.channel9.us

On 6/29/19, 16:00 Shawn Jackson <notifications@github.com> wrote:

@channel9network is it when your running the Resgrid.Console.exe dbupdate command? Did you install SQL Server Management studio as well? If so are you able to connect to the installed SQL Instance? Assuming you installed it in C:\Resgrid, there should be a file called ResgridConfig.json in C:\Resgrid\Config, a property there called DataConfig.ConnectionString will point to the database installation. If the installation is named that default connection string won't work.

**Comment by ucswift** [comment]
@channel9network I'll pull the code down to a test environment and set it up to see if I can find the issue as well. Do you remember what settings you used for SQL Server 2017 Express? That way I can set up my db the same as yours.

**Comment by channel9network** [comment]
Out of the box no specials
Jacob Pasley
CEO
Channel 9 Network
P: (502) 316-8060
W: www.channel9.us

On 7/2/19, 10:57 Shawn Jackson <notifications@github.com> wrote:

@channel9network I'll pull the code down to a test environment and set it up to see if I can find the issue as well. Do you remember what settings you used for SQL Server 2017 Express? That way I can set up my db the same as yours.

**Comment by ucswift** [comment]
@channel9network did you create an empty Resgrid database inside the SQL Server after you had it installed? I'm unable to replicate the error on my end, but I think it may be due to that. If you did can you paste in the full error your getting and your connection string and I can get that fixed.

**Comment by channel9network** [comment]
We stopped the project. I don't have the time to troubleshoot this. Sorry. Do you call provide install options? If we provide remote access?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by channel9network** [comment]
Shawn,

We are have some time to allocate to this. Project again. Can you advise the following:

Server OS preferred
SQL Server preferred
Resources needed for getting started. All of this will be virtual machines

Jacob Pasley

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by channel9network** [comment]
Also. What should the connection string look like for replacing it in the config file. I wish you guys had an installer platform to just install it on windows with all the steps in a GUI. Can I request that option for. The future?

**Comment by ucswift** [comment]
@channel9network Just wanted to circle back on this issue. While looking at issue #2 I found that instance names in connection strings for the config.json were not being processed correctly. In commit 2fada9a661b4e1f59948d36beea00fa880ad80fb I updated the documentation (https://resgrid-core.readthedocs.io/en/latest/installation/index.html#id3) that now calls out that a double backslash \\ is needed in between the server name and the instance name. I also added some console emits 
![2019-09-28 12_17_36-Window](https://user-images.githubusercontent.com/410646/65821423-21f7de00-e1ea-11e9-8246-60d0b2700bc6.png)
 so you know the ResgridConfig.json file was processed correctly and pointing to the correct server. I will be cutting a new release here in the next little bit with those changed included.

We recommend SQL 2016 SP1, but newer versions should work as well. Installed on Windows Server 2016 or newer. It is possible to run all of Resgrid on a non-server version of Windows, in that case,
 we recommend Windows 10.

Resources are dependant on load. For our test environments, I use VM's usually have them set up as dual CPU with 16GB of RAM and a 200GB disk. Depending on the load on the system, log and data retention and overall activity you will need to size the CPU, RAM, and disk appropriately. Resgrid is setup to span many multiple systems, for example, your own database server, web servers, application servers, log servers, rabbit mq messaging servers, etc. For highly mission-critical and/or high volume applications we strongly recommend a multiple system rollout.

**Comment by ucswift** [comment]
So an example connection string which utilizes a SQL instance name will look like this in the ResgridConfig.json file:
![2019-09-28 12_23_11-Window](https://user-images.githubusercontent.com/410646/65821474-ddb90d80-e1ea-11e9-9c1e-3e47ee8fa503.png)

**Comment by ucswift** [comment]
Cut a new release v0.15 and tested a few different scenarios and was able to get past the SQL connection issue. When you get a chance can you pull down that release and give it a test.

**Comment by channel9network** [comment]
I will setup a clean server and install and let you know how it works. Is there a plan in the future to have a Windows complete installer?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by channel9network** [comment]
I got the SQL Script to execute great! Finished the installation per the instruction and get this. Any ideas? I followed it to the letter. Running Windows Server 2012 R2 with all updates and service packs, MS SQL Server 2017 with default instance. IIS 10 with all the settings mentioned. All the other applications are already running in the services.
[cid:98194774-7a4c-4861-ba66-8dcfd039bff7]



Jacob W Pasley

CEO / Founder

Channel 9 Network

P: 1-502-316-8060

________________________________

**Comment by ucswift** [comment]
@channel9network Not seeing anything in the github issue comment (https://github.com/Resgrid/Core/issues/1#issuecomment-540346045) You may need to manually upload the attachment.

**Comment by channel9network** [comment]
Getting 500 error on webload

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ucswift** [comment]
@channel9network can you send the details of the 500 error? If your just getting a generic error page without details try viewing the page from the localhost server and that should give some error detail. Otherwise you should be able to get some information from the Windows Event Viewer.

**Comment by ucswift** [comment]
Close issue due to inactivity. If the issue is still occurring please open up a new issue and reference this one.
