### ISSUE TITLE
containers fail to start

### ISSUE THREAD

**Issue by netforce** [Resgrid/Core#10]
Trying to build the docker containers, which goes wel. untill they start.. Since i have no experience with dotnet building i'm not able to debug this..

Lets take this step by step;
* changed some ConnectionStrings in Core/Resgrid.Config/DataConfig.cs and /Core/Resgrid.Config/ServiceBusConfig.cs and updated the /Core/Resgrid.Config/ResgridConfig.json to match my seperate MSSQL and RabbitMQ server (also on Debian10)
* "docker-compose build" runs perfectly, only a 1000+ warnings, which seem to match the warnings of the github CI runs overhere at GitHub, so i'm not to worried about that.

- Operating system: Debian 10 
- docker-compose version 1.21.0
- Resgrid Core: latest git checkout

root@builder# docker-compose build
<snip> 
Successfully built f6efaa4016dc
Successfully tagged resgridwebcore:latest

Successfully built d00fbb294d48
Successfully tagged resgridwebservices:latest

root@builder# docker images
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
resgridwebservices                     latest              d00fbb294d48        About an hour ago   296MB
resgridwebcore                         latest              f6efaa4016dc        2 hours ago         436MB
mcr.microsoft.com/dotnet/core/sdk      3.1-buster          abac622402fa        15 hours ago        710MB
mcr.microsoft.com/dotnet/core/aspnet   3.1-buster-slim     96df76fbb586        6 days ago          207MB

root@builder# docker-compose up 
WARNING: The APPDATA variable is not set. Defaulting to a blank string.
Starting resgrid-core_resgrid.webcore_1          ... done
Starting resgrid-core_resgrid.web.servicescore_1 ... done
Attaching to resgrid-core_resgrid.web.servicescore_1, resgrid-core_resgrid.webcore_1
resgrid.webcore_1           | Unhandled exception. System.ArgumentException: is empty
resgrid.webcore_1           |    at StackExchange.Redis.ConfigurationOptions.DoParse(String configuration, Boolean ignoreUnknown) in /_/src/StackExchange.Redis/ConfigurationOptions.cs:line 634
resgrid.webcore_1           |    at StackExchange.Redis.ConfigurationOptions.Parse(String configuration) in /_/src/StackExchange.Redis/ConfigurationOptions.cs:line 419
resgrid.webcore_1           |    at StackExchange.Redis.ConnectionMultiplexer.PrepareConfig(Object configuration, Boolean sentinel) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 907
resgrid.webcore_1           |    at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1020
resgrid.webcore_1           |    at Resgrid.Web.Startup.ConfigureServices(IServiceCollection services) in /src/Web/Resgrid.WebCore/Startup.cs:line 280
resgrid.webcore_1           |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
resgrid.webcore_1           |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
resgrid.webcore_1           |    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
resgrid.webcore_1           |    at Microsoft.Extensions.Hosting.HostBuilder.Build()
resgrid.webcore_1           |    at Resgrid.Web.Program.Main(String[] args) in /src/Web/Resgrid.WebCore/Program.cs:line 25
resgrid.web.servicescore_1  | warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
resgrid.web.servicescore_1  |       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
resgrid-core_resgrid.webcore_1 exited with code 139
resgrid.web.servicescore_1  | info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
resgrid.web.servicescore_1  |       User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
resgrid.web.servicescore_1  | crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
resgrid.web.servicescore_1  |       Application startup exception
resgrid.web.servicescore_1  | Autofac.Core.DependencyResolutionException: An exception was thrown while activating Microsoft.AspNetCore.SignalR.HubConnectionHandler`1[[Resgrid.Web.Services.Hubs.EventingHub, Resgrid.Web.Services, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]] -> Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager`1[[Resgrid.Web.Services.Hubs.EventingHub, Resgrid.Web.Services, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]].
resgrid.web.servicescore_1  |  ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Logging.ILogger`1[Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager`1[Resgrid.Web.Services.Hubs.EventingHub]], Microsoft.Extensions.Options.IOptions`1[Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisOptions], Microsoft.AspNetCore.SignalR.IHubProtocolResolver, Microsoft.Extensions.Options.IOptions`1[Microsoft.AspNetCore.SignalR.HubOptions], Microsoft.Extensions.Options.IOptions`1[Microsoft.AspNetCore.SignalR.HubOptions`1[Resgrid.Web.Services.Hubs.EventingHub]])' on type 'RedisHubLifetimeManager`1'.
resgrid.web.servicescore_1  |  ---> System.ArgumentException: is empty
resgrid.web.servicescore_1  |    at StackExchange.Redis.ConfigurationOptions.DoParse(String configuration, Boolean ignoreUnknown) in /_/src/StackExchange.Redis/ConfigurationOptions.cs:line 634
resgrid.web.servicescore_1  |    at StackExchange.Redis.ConfigurationOptions.Parse(String configuration) in /_/src/StackExchange.Redis/ConfigurationOptions.cs:line 419
resgrid.web.servicescore_1  |    at Microsoft.Extensions.DependencyInjection.StackExchangeRedisDependencyInjectionExtensions.<>c__DisplayClass3_0.<AddStackExchangeRedis>b__0(RedisOptions o)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
resgrid.web.servicescore_1  |    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
resgrid.web.servicescore_1  |    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
resgrid.web.servicescore_1  |    at System.Lazy`1.CreateValue()
resgrid.web.servicescore_1  |    at System.Lazy`1.get_Value()
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager`1..ctor(ILogger`1 logger, IOptions`1 options, IHubProtocolResolver hubProtocolResolver, IOptions`1 globalHubOptions, IOptions`1 hubOptions)
resgrid.web.servicescore_1  |    at lambda_method(Closure , Object[] )
resgrid.web.servicescore_1  |    at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
resgrid.web.servicescore_1  |    --- End of inner exception stack trace ---
resgrid.web.servicescore_1  |    at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
resgrid.web.servicescore_1  |    at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
resgrid.web.servicescore_1  |    at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
resgrid.web.servicescore_1  |    --- End of inner exception stack trace ---
resgrid.web.servicescore_1  |    at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
resgrid.web.servicescore_1  |    at Autofac.Core.Resolving.InstanceLookup.<Execute>b__8_0()
resgrid.web.servicescore_1  |    at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
resgrid.web.servicescore_1  |    at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
resgrid.web.servicescore_1  |    at Autofac.Core.Resolving.InstanceLookup.Execute()
resgrid.web.servicescore_1  |    at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
resgrid.web.servicescore_1  |    at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
resgrid.web.servicescore_1  |    at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
resgrid.web.servicescore_1  |    at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
resgrid.web.servicescore_1  |    at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
resgrid.web.servicescore_1  |    at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
resgrid.web.servicescore_1  |    at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
resgrid.web.servicescore_1  |    at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)
resgrid.web.servicescore_1  |    at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstance[T](IServiceProvider provider)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Connections.ConnectionBuilderExtensions.UseConnectionHandler[TConnectionHandler](IConnectionBuilder connectionBuilder)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.SignalR.SignalRConnectionBuilderExtensions.UseHub[THub](IConnectionBuilder connectionBuilder)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Builder.HubEndpointRouteBuilderExtensions.<>c__1`1.<MapHub>b__1_0(IConnectionBuilder b)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Builder.ConnectionEndpointRouteBuilderExtensions.MapConnections(IEndpointRouteBuilder endpoints, String pattern, HttpConnectionDispatcherOptions options, Action`1 configure)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Builder.HubEndpointRouteBuilderExtensions.MapHub[THub](IEndpointRouteBuilder endpoints, String pattern, Action`1 configureOptions)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Builder.HubEndpointRouteBuilderExtensions.MapHub[THub](IEndpointRouteBuilder endpoints, String pattern)
resgrid.web.servicescore_1  |    at Resgrid.Web.ServicesCore.Startup.<>c.<Configure>b__19_4(IEndpointRouteBuilder endpoints) in /src/Web/Resgrid.Web.ServicesCore/Startup.cs:line 396
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
resgrid.web.servicescore_1  |    at Resgrid.Web.ServicesCore.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in /src/Web/Resgrid.Web.ServicesCore/Startup.cs:line 397
resgrid.web.servicescore_1  |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
resgrid.web.servicescore_1  |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.DependencyInjection.AutoRegisterMiddleware.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
resgrid.web.servicescore_1  |    at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
resgrid.web.servicescore_1  | Unhandled exception. Autofac.Core.DependencyResolutionException: An exception was thrown while activating Microsoft.AspNetCore.SignalR.HubConnectionHandler`1[[Resgrid.Web.Services.Hubs.EventingHub, Resgrid.Web.Services, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]] -> Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager`1[[Resgrid.Web.Services.Hubs.EventingHub, Resgrid.Web.Services, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]].
resgrid.web.servicescore_1  |  ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Logging.ILogger`1[Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager`1[Resgrid.Web.Services.Hubs.EventingHub]], Microsoft.Extensions.Options.IOptions`1[Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisOptions], Microsoft.AspNetCore.SignalR.IHubProtocolResolver, Microsoft.Extensions.Options.IOptions`1[Microsoft.AspNetCore.SignalR.HubOptions], Microsoft.Extensions.Options.IOptions`1[Microsoft.AspNetCore.SignalR.HubOptions`1[Resgrid.Web.Services.Hubs.EventingHub]])' on type 'RedisHubLifetimeManager`1'.
resgrid.web.servicescore_1  |  ---> System.ArgumentException: is empty
resgrid.web.servicescore_1  |    at StackExchange.Redis.ConfigurationOptions.DoParse(String configuration, Boolean ignoreUnknown) in /_/src/StackExchange.Redis/ConfigurationOptions.cs:line 634
resgrid.web.servicescore_1  |    at StackExchange.Redis.ConfigurationOptions.Parse(String configuration) in /_/src/StackExchange.Redis/ConfigurationOptions.cs:line 419
resgrid.web.servicescore_1  |    at Microsoft.Extensions.DependencyInjection.StackExchangeRedisDependencyInjectionExtensions.<>c__DisplayClass3_0.<AddStackExchangeRedis>b__0(RedisOptions o)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
resgrid.web.servicescore_1  |    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
resgrid.web.servicescore_1  |    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
resgrid.web.servicescore_1  |    at System.Lazy`1.CreateValue()
resgrid.web.servicescore_1  |    at System.Lazy`1.get_Value()
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager`1..ctor(ILogger`1 logger, IOptions`1 options, IHubProtocolResolver hubProtocolResolver, IOptions`1 globalHubOptions, IOptions`1 hubOptions)
resgrid.web.servicescore_1  |    at lambda_method(Closure , Object[] )
resgrid.web.servicescore_1  |    at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
resgrid.web.servicescore_1  |    --- End of inner exception stack trace ---
resgrid.web.servicescore_1  |    at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
resgrid.web.servicescore_1  |    at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
resgrid.web.servicescore_1  |    at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
resgrid.web.servicescore_1  |    --- End of inner exception stack trace ---
resgrid.web.servicescore_1  |    at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
resgrid.web.servicescore_1  |    at Autofac.Core.Resolving.InstanceLookup.<Execute>b__8_0()
resgrid.web.servicescore_1  |    at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
resgrid.web.servicescore_1  |    at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
resgrid.web.servicescore_1  |    at Autofac.Core.Resolving.InstanceLookup.Execute()
resgrid.web.servicescore_1  |    at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
resgrid.web.servicescore_1  |    at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
resgrid.web.servicescore_1  |    at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
resgrid.web.servicescore_1  |    at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
resgrid.web.servicescore_1  |    at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
resgrid.web.servicescore_1  |    at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
resgrid.web.servicescore_1  |    at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
resgrid.web.servicescore_1  |    at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType)
resgrid.web.servicescore_1  |    at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetService(Type serviceType)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstance[T](IServiceProvider provider)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Connections.ConnectionBuilderExtensions.UseConnectionHandler[TConnectionHandler](IConnectionBuilder connectionBuilder)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.SignalR.SignalRConnectionBuilderExtensions.UseHub[THub](IConnectionBuilder connectionBuilder)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Builder.HubEndpointRouteBuilderExtensions.<>c__1`1.<MapHub>b__1_0(IConnectionBuilder b)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Builder.ConnectionEndpointRouteBuilderExtensions.MapConnections(IEndpointRouteBuilder endpoints, String pattern, HttpConnectionDispatcherOptions options, Action`1 configure)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Builder.HubEndpointRouteBuilderExtensions.MapHub[THub](IEndpointRouteBuilder endpoints, String pattern, Action`1 configureOptions)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Builder.HubEndpointRouteBuilderExtensions.MapHub[THub](IEndpointRouteBuilder endpoints, String pattern)
resgrid.web.servicescore_1  |    at Resgrid.Web.ServicesCore.Startup.<>c.<Configure>b__19_4(IEndpointRouteBuilder endpoints) in /src/Web/Resgrid.Web.ServicesCore/Startup.cs:line 396
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
resgrid.web.servicescore_1  |    at Resgrid.Web.ServicesCore.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in /src/Web/Resgrid.Web.ServicesCore/Startup.cs:line 397
resgrid.web.servicescore_1  |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
resgrid.web.servicescore_1  |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.DependencyInjection.AutoRegisterMiddleware.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
resgrid.web.servicescore_1  |    at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
resgrid.web.servicescore_1  |    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
resgrid.web.servicescore_1  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
resgrid.web.servicescore_1  |    at Resgrid.Web.ServicesCore.Program.Main(String[] args) in /src/Web/Resgrid.Web.ServicesCore/Program.cs:line 14
resgrid-core_resgrid.web.servicescore_1 exited with code 139
root@builder#

**Comment by ucswift** [comment]
Hey,
  Its failing due to the correct env variables not being set, connection strings to redis, rabbitmq and sql server. I'm working on the documentation update for the container deployment.

**Comment by netforce** [comment]
Hello Ucswift,

hm, i thought i tackled those errors by changing the BusValues and Connectionstrings in DataConfig.cs and ServiceBusConfig.cs, next to the ResgridConfig.json. Because it looked like the vars from ResgridConfig.json were overruled by those in de .cs files..

I'l be waiting for the documentation :)

**Comment by ucswift** [comment]
For containers, I added support to set the values via environment variables. The pattern for the name is "RESGRID__" + the Config file name + "__" + the Property your setting, for example:

RESGRID__CacheConfig__RedisConnectionString

Note, Resgrid needs to be in all caps, and it's double underscores that separate the parts.

The most important values to set:

RESGRID__CacheConfig__RedisConnectionString
RESGRID__DataConfig__ConnectionString
RESGRID__ServiceBusConfig__RabbbitPassword
RESGRID__ServiceBusConfig__RabbitHostname
RESGRID__ServiceBusConfig__RabbitUsername
RESGRID__SystemBehaviorConfig__ResgridApiBaseUrl:
RESGRID__SystemBehaviorConfig__ResgridBaseUrl:

For the others, the defaults should allow the container to startup correctly.

**Comment by netforce** [comment]
ah pfrt, good evening (and the best wishes)! 

i overlooked the RedisConnectionString. Some playing around and reading manuals for redis on dotnet applications got it working. e.g the containers boot. 

changes made to the docker-compose.yml;
[...]
   image: ${DOCKER_REGISTRY-}resgridwebcore
+    env_file: resgrid-docker.env
[...]
   image: ${DOCKER_REGISTRY-}resgridwebservices
+    env_file: resgrid-docker.env

contents of resgrid-docker.env:
RESGRID__CacheConfig__RedisConnectionString=x.x.x.x:6379,Password=****,allowAdmin=True
RESGRID__DataConfig__ConnectionString=Server=x.x.x.x;Database=Resgrid;User Id=resgrid_app;Password=****;MultipleActiveResultSets=True;
RESGRID__ServiceBusConfig__RabbbitPassword=****
RESGRID__ServiceBusConfig__RabbitHostname=x.x.x.x
RESGRID__ServiceBusConfig__RabbitUsername=resgrid
RESGRID__SystemBehaviorConfig__ResgridApiBaseUrl="http://domain.example:80/api"
RESGRID__SystemBehaviorConfig__ResgridBaseUrl="http://domain.example:80"

**Comment by netforce** [comment]
minor note on the above env/docker-compose file;
- lose the quotes in the BaseUrl lines
- added portmappings in the docker-compose files for both containers. Base: port 80:80, Api: port 80:81
- changed the api BaseURL to http://domain.example:81
`
[...]
image: ${DOCKER_REGISTRY-}resgridwebcore
env_file: 
  - resgrid-docker.env
ports:
  - "80:80"
[...]
image: ${DOCKER_REGISTRY-}resgridwebservices
env_file: 
  - resgrid-docker.env
ports:
  - "80:81"
`

contents of resgrid-docker.env:

`
RESGRID__CacheConfig__RedisConnectionString=x.x.x.x:6379,Password=,allowAdmin=True
RESGRID__DataConfig__ConnectionString=Server=x.x.x.x;Database=Resgrid;User Id=resgrid_app;Password=;MultipleActiveResultSets=True;
RESGRID__ServiceBusConfig__RabbbitPassword=****
RESGRID__ServiceBusConfig__RabbitHostname=x.x.x.x
RESGRID__ServiceBusConfig__RabbitUsername=resgrid
RESGRID__SystemBehaviorConfig__ResgridApiBaseUrl=http://domain.example:81
RESGRID__SystemBehaviorConfig__ResgridBaseUrl=http://domain.example:80
`

**Comment by ucswift** [comment]
With the v0.5.30 we have tested containers with Fedora 35 and Ubuntu 20.04. In the Docker folder in the repo there is a resgrid.env file that notes all the needed values for the containers. If you have any issues with that release please open up a new issue.
