### ISSUE TITLE
Documentation: Local install

### ISSUE THREAD

**Issue by fasteddys** [Resgrid/Core#101]
Hello @ucswift any chance you leave the local install instructions up, I am not sure how to debug and add new features into the core.

**Comment by ucswift** [comment]
@fasteddys for local development or testing/use?

**Comment by ucswift** [comment]
Hey @fasteddys for a local instance that can be used to get up and running right out of the gate we have some documentation https://docs.resgrid.com/get-started/quick-start but for local dev I have not gotten that far yet. 

As a platform, the only type of install I'll be supporting is Docker based ones as this is how I run the system for the hosted version it allowed me to ensure that the code base is working exactly as it should. I tried to do the file based path and there were too many additional environment issues that ate up time helping debug those issues.

I've been trying to split individual components into their own containers, which allows for more horizontal scaling and orchestration. It does app complications but I've been trying to abstract that away on the small installs with an easy docker compose setup https://github.com/Resgrid/resgrid-setup/blob/master/docker-compose.yml
