### ISSUE TITLE
Bug: Self hosted checking for more than one payment for department.

### ISSUE THREAD

**Issue by Shuttleu** [Resgrid/Core#106]
https://github.com/Resgrid/Core/blob/6f0f7f0f098bc51c0b8bc2a2c3c8d3376bcd5336/Repositories/Resgrid.Repositories.DataRepository/IdentityRepository.cs#L169C18-L169C18
https://github.com/Resgrid/Core/blob/6f0f7f0f098bc51c0b8bc2a2c3c8d3376bcd5336/Repositories/Resgrid.Repositories.DataRepository/IdentityRepository.cs#L195C18-L169C18

When getting the list of users while on self hosted via Docker, we can add as many users as we wish, however only 10 will show up on the web front end.
Looking into this I have narrowed it down to a SQL statement checking if we have made more than one payment.

The system creates a payment when the department is created, however as the SQL query is checking for more than one payment, it falls back to the default of 10.

Creating a second payment in the database allows the system to check the plan and allow the fill number of users.

I have linked the two lines which should be `>=` instead of `>`

**Comment by ucswift** [comment]
@Shuttleu thanks for reporting this, I'm working on a fix now
