### ISSUE TITLE
Running ResGrid in Isolation

### ISSUE THREAD

**Issue by mgti** [Resgrid/Core#11]
Hello Resgrid team, I have a scenario where I'm trying to run ResGrid in an isolated environment without access to the internet. While using the open source version in isolation a few features are not working, such as the Personnel panel on the Home dashboard and the Top Right Drop Down Menu's. Testing access to Resgrid while running Wireshark and IE Developer Tools option enable shows the application making a few calls out to the internet.  Is there a way to run Resgrid without internet access?

**Comment by ucswift** [comment]
Hey @mgti what calls are going out? You should be able to run the system as it should fallback to local options of js dependencies if it can't pull them from a CDN. If those are missing it could cause the issue. The intent is you can run the system completely isolated, but some systems, like Push Notifications, won't work in that state, but most of the system will be functional.

**Comment by mgti** [comment]
Thanks for the quick response, here's a list of 3rd party calls that I've documented going out to load various js and other items, and when the clients fails to access (in the case when running Resgrid and clients in an isolated environment) some of the panels and other functions are failing:

ajax.googleapis.com
api.resgrid.com
az416426.vo.msecnd.net
fonts.googleapis.com
fonts.gstatsic.com
maps.gstatsic.com
js.stripe.com
maps.googleapis.com (we don't need map functionality, so this is not an issue)
maxcdn.bootstrapcdn.com

Some of the functions that stop working with clients\resgrid server in isolation are:
- Help Drop Down Menu
- Main Drop Down Menu
- User Profile Drop Down Menu (under user profile picture)
- defaultProfile.png User Picture fails to load
- Personnel List on Home Dashboard does not load
- Personnel list on Personnel Dashboard
- Calls on Calls Dashboard
- Shifts list and Calendar on Shift Dashboard
- Unit status does not load
Apparently it's the scripts used to render all the lists
This can be replicated running Resgrid in vmware, disabling network connectivity and testing access to Resgrid from within the VM. 

![Screen Shot 2020-12-31 at 09 38 45](https://user-images.githubusercontent.com/76750774/103420640-2b8a9700-4b4d-11eb-8ff7-713de4904fb4.png)

Any thoughts on best approach to have that functionality working while isolating clients\server are much appreciated. My initial take to make this work in my test environment is to document all the calls and locate the files that have the URL references and edit them to use local content. 

Thanks in advance!!
Awesome App BTW :)

**Comment by ucswift** [comment]
Thanks for that list, it helps a ton! Just going through it the gstatic ones should be fine, and the mapping ones won't work, but we are looking at migrating from Google Maps to Open Street Maps that would allow you to run an on-prem tile server for those. Stripe is our payment provider and not needed for on-prem installs and can be safely ignored. The big ones that I think could be causing you problems is that there is a call going out to api.resgrid.com, those should be pointing to your on-prem api endpoint and not our hosted version. The other ones are bootstrapcdn, msecnd that I worry could be not falling back to bundled versions of those apis.

If you could run the DevTools console on the Dashboard page and share the errors from that, it should help me identify the missing libs.

As for the best approach, the system *should* mostly function in isolation, it will try and make calls out, but fallback if they don't work. Other features like Push Notifications, Text Messaging, etc do require an external provider, but at the Personnel level if those options aren't checked it should even attempt to make those calls.

**Comment by mgti** [comment]
>> Here are the errors from the DebugTools Console , with the server/client in isolation:

SCRIPT5007: Unable to get property 'fn' of undefined or null reference
File: metisMenu.min.js, Line: 8, Column: 970
SCRIPT5009: 'jQuery' is undefined
File: jquery.slimscroll.min.js, Line: 8, Column: 2
SCRIPT5009: 'jQuery' is undefined
File: select2.full.min.js, Line: 1, Column: 319
SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.
File: Dashboard
SCRIPT5009: 'jQuery' is undefined
File: kendo.web.min.js, Line: 25, Column: 71
SCRIPT5009: 'google' is undefined
File: markerwithlabel.js, Line: 82, Column: 1
SCRIPT5009: 'jQuery' is undefined
File: jquery-ujs.js, Line: 1, Column: 2
SCRIPT5009: 'jQuery' is undefined
File: jquery-ui.min.js, Line: 6, Column: 73
SCRIPT5022: jQuery was not found. Please ensure jQuery is referenced before the SignalR client JavaScript file.
File: jquery.signalR-2.2.0.min.js, Line: 8, Column: 2885
SCRIPT5009: 'jQuery' is undefined
File: picedit.min.js, Line: 7, Column: 2
SCRIPT5007: Unable to get property 'fn' of undefined or null reference
File: bootstrap-wizard.min.js, Line: 1, Column: 17
SCRIPT5009: 'jQuery' is undefined
File: jquery.validate.min.js, Line: 4, Column: 149
SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.
File: Dashboard
SCRIPT5007: Unable to get property 'extend' of undefined or null reference
File: fullcalendar.min.js, Line: 6, Column: 15602
SCRIPT5009: 'jQuery' is undefined
File: jquery.validate.unobtrusive.min.js, Line: 5, Column: 201
SCRIPT5009: '$' is undefined
File: site.min.js, Line: 1, Column: 588
SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.
File: Dashboard
SCRIPT5009: '$' is undefined
File: resgrid.user.js, Line: 14, Column: 9
SCRIPT5009: '$' is undefined
File: resgrid.home.dashboard.js, Line: 7, Column: 13
SCRIPT5009: '$' is undefined
File: Dashboard, Line: 449, Column: 2
SCRIPT5009: '$' is undefined
File: resgrid.js, Line: 7, Column: 9
SCRIPT7002: XMLHttpRequest: Network Error 0x80070005, Access is denied.
File: Dashboard

>> There is an additional 1 Warning

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: Dashboard

>> I'm also adding output from the DevTools Console when the Virtual Machine (Resgrid Server & Client) can connect to the internet . There are 0 errors and 5 warning. 

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: Dashboard
Unknown DataSource transport type 'json'.
Verify that registration scripts for this type are included after Kendo UI on the page.
Unknown DataSource transport type 'json'.
Verify that registration scripts for this type are included after Kendo UI on the page.
Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
Google Maps JavaScript API warning: InvalidKey https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key

Once again thank you for the quick response and help!!

**Comment by ucswift** [comment]
Ok yep, the jquery fallback is not working, causing your issue. I'll take a look at this in the code I'm about to push up to github to see if I can get that resolved.

**Comment by ucswift** [comment]
@mgti I've pushed up a commit with a fix for this issue (https://github.com/Resgrid/Core/blob/master/Web/Resgrid.WebCore/Areas/User/Views/Shared/_UserLayout.cshtml#L92) this will properly fallback if it cannot get Bootstrap or jQuery from the CDN or if the hash is invalid. So that fix will be in the next code and Docker release which I'm working on now.

**Comment by mgti** [comment]
Thanks @ucswift, I'll be testing the fix this week and will keep you posted. 
I appreciate the help and quick turn around.

**Comment by ucswift** [comment]
Hey, @mgti I'll be pushing out a release hopefully sometime this week. The version number will be 0.3.x when it's up and will contain this fix. I'm working on the CI pipeline this week to generate the package I need for the Github release.

**Comment by mgti** [comment]
@ucswift, I tested the patch and got a 500 error after login. 
Just for info, HTTP 404 for these two files:
     GET     /lib/metisMenu/dist/metisMenu.min.css
     GET     /lib/bootstrap/dist/css/bootstrap.min.css
And a 500 for this POST
      POST https://<fqdn>/User/Home/Dashboard
I restored the original _UserLayout.cshtml and will hold off any further testing\troubleshooting and pull the new release when available. Once again, thank you for your help.

**Comment by ucswift** [comment]
Hello,
   It took a month longer than I wanted but the 0.3 release is out there https://github.com/Resgrid/Core/releases/tag/v0.3.25 which has some isolation/offline fixes. I'll close this issue, if you run into any more please open another issue.
