### ISSUE TITLE
AzureEventing called when IsAzure=false 

### ISSUE THREAD

**Issue by netforce** [Resgrid/Core#12]
It seems that AzureEventing is called on several occasions, which results in crashing the resgrid-web container.

These containers are not running on azure, so i would guess, when my setting SystemBehaviourConfig.IsAzure=false, the Azure eventing service is not called upon.

The event (adding a call, or some user changing his availability) is processed corectly when restarting the container, so thats's OK. But calling the AzureEventing Service seems a bit wrong to me. 
Or am i missing something here?

root@builder:/home/resgrid/Resgrid-core# docker-compose up
WARNING: The APPDATA variable is not set. Defaulting to a blank string.
Starting resgrid-core_resgrid.web.servicescore_1 ... done
Starting resgrid-core_resgrid.webcore_1          ... done
Attaching to resgrid-core_resgrid.web.servicescore_1, resgrid-core_resgrid.webcore_1
resgrid.web.servicescore_1  | Resgrid.Config: Setting Value for System.String WorkerDbConnectionString
resgrid.web.servicescore_1  | Resgrid.Config: Setting Value for System.String ResgridBaseUrl
resgrid.web.servicescore_1  | Resgrid.Config: Setting Value for System.String ResgridApiBaseUrl
resgrid.web.servicescore_1  | Resgrid.Config: Setting Value for System.String RabbitUsername
resgrid.web.servicescore_1  | Resgrid.Config: Setting Value for System.String RabbitHostname
resgrid.web.servicescore_1  | Resgrid.Config: Setting Value for System.String RabbbitPassword
resgrid.web.servicescore_1  | Resgrid.Config: Setting Value for System.String ConnectionString
resgrid.web.servicescore_1  | Resgrid.Config: Setting Value for System.String RedisConnectionString
resgrid.webcore_1           | Resgrid.Config: Setting Value for System.String WorkerDbConnectionString
resgrid.webcore_1           | Resgrid.Config: Setting Value for System.String ResgridBaseUrl
resgrid.webcore_1           | Resgrid.Config: Setting Value for System.String ResgridApiBaseUrl
resgrid.webcore_1           | Resgrid.Config: Setting Value for System.String RabbitUsername
resgrid.webcore_1           | Resgrid.Config: Setting Value for System.String RabbitHostname
resgrid.webcore_1           | Resgrid.Config: Setting Value for System.String RabbbitPassword
resgrid.webcore_1           | Resgrid.Config: Setting Value for System.String ConnectionString
resgrid.webcore_1           | Resgrid.Config: Setting Value for System.String RedisConnectionString
resgrid.web.servicescore_1  | warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
resgrid.web.servicescore_1  |       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
resgrid.web.servicescore_1  | info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
resgrid.web.servicescore_1  |       User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
resgrid.web.servicescore_1  | info: Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager[1]
resgrid.web.servicescore_1  |       Connecting to Redis endpoints: x.x.x.x:6379. Using Server Name: fcc9af640022_a094cb391ed24e52ab34b70cf74845ee
resgrid.web.servicescore_1  | info: Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager[2]
resgrid.web.servicescore_1  |       Connected to Redis.
resgrid.web.servicescore_1  | info: Microsoft.Hosting.Lifetime[0]
resgrid.web.servicescore_1  |       Now listening on: http://[::]:80
resgrid.web.servicescore_1  | info: Microsoft.Hosting.Lifetime[0]
resgrid.web.servicescore_1  |       Application started. Press Ctrl+C to shut down.
resgrid.web.servicescore_1  | info: Microsoft.Hosting.Lifetime[0]
resgrid.web.servicescore_1  |       Hosting environment: Production
resgrid.web.servicescore_1  | info: Microsoft.Hosting.Lifetime[0]
resgrid.web.servicescore_1  |       Content root path: /app
resgrid.webcore_1           | Unhandled exception. System.ArgumentException: The argument namespaceConnectionString is null or white space. (Parameter 'namespaceConnectionString')
resgrid.webcore_1           |    at Microsoft.Azure.ServiceBus.ServiceBusConnection..ctor(String namespaceConnectionString, RetryPolicy retryPolicy)
resgrid.webcore_1           |    at Resgrid.Providers.Bus.OutboundEventProvider.<>c.<<-ctor>b__4_30>d.MoveNext() in /src/Providers/Resgrid.Providers.Bus/OutboundEventProvider.cs:line 1396
resgrid.webcore_1           | --- End of stack trace from previous location where exception was thrown ---
resgrid.webcore_1           |    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
resgrid.webcore_1           |    at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
resgrid.webcore_1           |    at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
resgrid.webcore_1           |    at System.Threading.QueueUserWorkItemCallback.Execute()
resgrid.webcore_1           |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
resgrid-core_resgrid.webcore_1 exited with code 139

**Comment by netforce** [comment]
on further investigation, and after trying to change notifications in domain.example/User/Notifications i get an error 500 entering User/Notifications . Maybe related tot any notifications?

resgrid.web.servicescore_1  |       Content root path: /app
resgrid.webcore_1           | fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
resgrid.webcore_1           |       An unhandled exception has occurred while executing the request.
resgrid.webcore_1           | System.NullReferenceException: Object reference not set to an instance of an object.
resgrid.webcore_1           |    at Resgrid.Web.Areas.User.Controllers.NotificationsController.Index() in /src/Web/Resgrid.WebCore/Areas/User/Controllers/NotificationsController.cs:line 48
resgrid.webcore_1           |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
resgrid.webcore_1           |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by ucswift** [comment]
@netforce AzureEventing should be left on by default, even in a NonAzure env. But you want to change https://github.com/Resgrid/Core/blob/master/Core/Resgrid.Config/SystemBehaviorConfig.cs#L93 so that's it's using Rabbit, should be by default. I'll also take another pass at that startup logic to ensure it doesn't try and connect when not using the Azure Service Bus. 

The notification one is a bug, I just traced that code down and it got missed during the .Net Core update.

**Comment by ucswift** [comment]
I just pushed up https://github.com/Resgrid/Core/commit/a87c010069ba229e72ac2cd367b36c70849b2c4f which is a fix for the notification exception in the controller. I'm going to double-check the app state with IsAzure = false but if I remember right, as long as the SystemBehaviorConfig's are set up to not use an Azure resource, i.e. Service Bus, it should be fine.

**Comment by netforce** [comment]
Just pulled and merged the last code from here.

> @netforce AzureEventing should be left on by default, even in a NonAzure env. But you want to change https://github.com/Resgrid/Core/blob/master/Core/Resgrid.Config/SystemBehaviorConfig.cs#L93 so that's it's using Rabbit, should be by default. I'll also take another pass at that startup logic to ensure it doesn't try and connect when not using the Azure Service Bus.

In SystemBehaviourConfig.cs line 93 is on Rabbit, as default indeed.

In the Resgridconfig.json nothing is set for the BusConfig, as by default.

 root@resgrid-docker:/home/eelco/Resgrid-core# cat Core/Resgrid.Config/ResgridConfig.json  | grep BusConfig
  "ServiceBusConfig.RabbitHostname": "rgdevserver",
  "ServiceBusConfig.RabbitUsername": "resgrid",
  "ServiceBusConfig.RabbbitPassword": "resgrid",
  "ServiceBusConfig.RabbbitExchange": "",
  "ServiceBusConfig.SignalRServiceBusConnectionString": "",
  "ServiceBusConfig.SignalRTopicName": "",
  "ServiceBusConfig.AzureQueueSystemConnectionString": "",
  "ServiceBusConfig.SystemQueueName": "",
  "ServiceBusConfig.AzureEventingTopicConnectionString": "",
  "ServiceBusConfig.EventingTopicQueueName": "",
  "ServiceBusConfig.AzureNotificationHub_FullConnectionString": "",
  "ServiceBusConfig.AzureNotificationHub_PushUrl": "",
  "ServiceBusConfig.AzureServiceBusConnectionString": "",
  "ServiceBusConfig.AzureServiceBusWorkerConnectionString": "",
  "ServiceBusConfig.AzureQueueConnectionString": "",
  "ServiceBusConfig.AzureQueueMessageConnectionString": "",
  "ServiceBusConfig.AzureQueueNotificationConnectionString": "",
  "ServiceBusConfig.AzureQueueShiftsConnectionString": "",
  "ServiceBusConfig.AzureQueueEmailConnectionString": "",
  "ServiceBusConfig.AzureUnitNotificationHub_FullConnectionString": "",
  "ServiceBusConfig.AzureUnitNotificationHub_PushUrl": "",

Still crashing the container because it seems to expect some confguration for the Azure namespaceConnectionString from OutboundEventProvider.cs:line 1126, which points to Config.ServiceBusConfig.AzureServiceBusWorkerConnectionString
`
resgrid.webcore_1           | Unhandled exception. System.ArgumentException: The argument namespaceConnectionString is null or white space. (Parameter 'namespaceConnectionString')
resgrid.webcore_1           |    at Microsoft.Azure.ServiceBus.ServiceBusConnection..ctor(String namespaceConnectionString, RetryPolicy retryPolicy)
resgrid.webcore_1           |    at Resgrid.Providers.Bus.OutboundEventProvider.<>c.<<-ctor>b__4_27>d.MoveNext() in /src/Providers/Resgrid.Providers.Bus/OutboundEventProvider.cs:line 1126`

**Comment by ucswift** [comment]
@netforce Thanks for that research, I'll add some guarding code to prevent it from calling/getting hit when that isn't set. The test env we use for validation has a diff config which is why I didn't catch that in that env.

**Comment by ucswift** [comment]
Pushed up commit https://github.com/Resgrid/Core/commit/8a185d68fc58d8de4de25cbca02e07efff9bc74c that fixes the but in the outbound event provider that was still calling the Azure service bus code even when Rabbit was selected. That will make it into the next update of the containers which I'm working on now.

**Comment by ucswift** [comment]
FYI, I'm working on the CI infrastructure to work on pushing out the containers to DockerHub. There was some pre-work I needed to do to the Proxmox host to enable the functionality required. I got that done and will be working on the CI pipeline this week.

**Comment by ucswift** [comment]
Hello,
  Sorry for the delay, the latest release https://github.com/Resgrid/Core/releases/tag/v0.3.25 also has new docker containers pushed for it that have a fix for this issue in them. If you run into any more issues please open up another issue.
