### ISSUE TITLE
Public Free Account Sign Up Broken

### ISSUE THREAD

**Issue by pyhton-coder** [Resgrid/Core#142]
I am testing this software out and I think its super cool. I just found it a few days ago. However my self hosted experience has been slow and painful thus far. While I grind to get things set up I wanted to try out the free account from the site. However I am unable to create an account. When clicking submit... nothing happens. 

Included are the logs of the browser console when loading the registration page.

Tested Platforms:

Windows 11:
* Chrome
* Edge

Manjaro Linux:
* Chrome
* Firefox

MacOS Big Sir:
* Safari
* Chrome
![Screenshot 2024-07-02 190807](https://github.com/Resgrid/Core/assets/174559697/926b9b20-b21e-4e26-9004-3511f3374449)

**Comment by ucswift** [comment]
@pyhton-coder, thanks for reporting! I guess I broke that when I was cleaning up some styles. I'll get a fix in right now.

**Comment by ucswift** [comment]
@pyhton-coder a broken container made it out to prod, I generated a new one and the errors seem to have been resolved. Can you give it another try and let me know.

**Comment by ucswift** [comment]
@pyhton-coder I wanted to let you know I pushed up new quick-start docs (https://docs.resgrid.com/self-hosted/quick-start) and new setup docker-compose to the setup repo. If you are still having issues with the self hosted stuff open up a new issue.

**Comment by pyhton-coder** [comment]
So... I used the site and I must say! Much better. I wasn't exactly sure what was going on there. However I have tested making a new account successfully. pyhtoncoder was the account user name. It seems to work pretty well. TBH much better than my installation. It gives me something to work towards. However I did run into an issue when updating/pruning. I ran a docker-system prune -a with regrid docker container in the down state. I now am having issues.
<img width="1375" alt="Screenshot 2024-07-10 at 10 33 24 PM" src="https://github.com/Resgrid/Core/assets/174559697/27161c64-3fd7-4511-8a57-e306d48abebf">

I am totally fine with a fresh install. However even that didn't seem to work. I tried removing the db and docker-data directories as I wasn't super worried about the current deployment. However that also didn't work when trying to do a new build.
<img width="806" alt="Screenshot 2024-07-10 at 11 08 36 PM" src="https://github.com/Resgrid/Core/assets/174559697/1f9524fb-1bc9-4162-9601-e833d438962c">

So I wrote in a "Dockerfile" but left it blank as i'm not sure what to fill it with. Im working remote right now and kinda busy. However this week end I will have more time to dig in. I did take notes when installing the first time and I can probably get it running it again. However I mainly wanted you to know I did test and things on the public site not only look way better but also do function as expected. When signing in I was able to play with the software a bit. I mainly just left it for now. I wanted to see if I can get mine running. However as described it didn't seem to be working out for me. I'll go in this weekend and see if I can get a Dockerfile in and solve this issue. Also as the newbie here some background on me and my deployment: pyhtoncoder or Newt is ok too. I own an IT company in Idaho Falls, ID. I offer tech services as well as on-site PC/Server or even network repair. As such I am looking for a solid way to manage tickets and mainly dispatches for techs. I am currently using a paid software called gocanvas. However I do the Resgrid platform. As a lot of Resgrids core components are windows driven I am unfamiliar with the platform and will be doing a lot of learning along the way. I plan to be an active member here to help and learn about this software. Not a fan of anyting Microsoft for my own deployments. I do however have a few limited windows installations for some clients. My access with those systems is limited and I am learning on that front too. So... probably a lot of questions about the windows DB. It was the bane of my first deployment it seems to be a main issue here as well. I may have given up hope on this install but solving this issue will be curtail for me as I can't have deployments randomly disappearing do to a docker prune. Anyway super stoked to get into this software and try it out. I'd also love an estimate for paid support. I'm not afraid of that ether. I do like go canvas but in the end my custom stack will be much better than using 3 or 4 paid tools without API integration. Great work guys and tanks for such a warm welcome to the team. I will def check out your install guides listed for reinstalltion.

**Comment by ucswift** [comment]
The db dockerfile should be there https://github.com/Resgrid/resgrid-setup/blob/master/db/Dockerfile did you re-clone the setup repo? There should be directories for db and docker-data.

If the images are active they shouldn't be pruned once your system is running and that's how you'll get latest code when you want to update; (shut down the system, prune, and repull). All your custom data should be in the docker-data folder (i.e. the SQL database) and should survive pruning unless the volumes are also removed during that process.

**Comment by pyhton-coder** [comment]
I guess I did not. I thought when doing a docker-compose up after a shutdown and prune repulls everything as it no longer has the "Images" to do the job. It would not pull. It gave me the screen shot issues. As I work today I will try to go in and start over. Like I mentioned I'm down to start all over. I just need to do so.

**Comment by ucswift** [comment]
You could copy off the docker-data directory and .env file re-clone via git the setup repo and move the docker-data back, that should keep all your volumes/data in tact, the only thing you would need to do is create a caddy directory in docker-data and add the file https://github.com/Resgrid/resgrid-setup/commit/75a953b6825ddbe03f61afb712fe4940c22b2010

There were .env file changes https://github.com/Resgrid/resgrid-setup/commit/b73e55dd8b5cb0f28ce20695acb9f4c77a016e32  so you will need to just add the new stuff NGINX_RESGRID_WEB_IP, NGINX_RESGRID_API_IP and NGINX_RESGRID_EVENTS_IP are the big ones for Caddy.
