### ISSUE TITLE
Migration SQL script contains typo

### ISSUE THREAD

**Issue by anewio** [Resgrid/Core#18]
Trying to initialize database scheme by executing migration script: ResGrid.Core\Providers\Resgrid.Providers.Migrations\Sql\M0001_InitialMigration.sql, I encountered a SQL error on line 2858:
`ALTER TABLE [dbo].[Payments] ADD  DEFAULT ('1900-01-01T00:00:00.000') FOR [Endinn]`

After a quick troubleshooting, I believe `[Endinn]` is likely a typo and should be `[EndingOn]` which is a column of table `dbo.Payments`.  Please have a look. If you wish, I could submit my pull request once you agree.

**Comment by ucswift** [comment]
Hey @anewio thanks for the issue! I'm looking into it right now and will get a fix in.

**Comment by ucswift** [comment]
Issue fixed in this commit https://github.com/Resgrid/Core/commit/ae713a608c69dbf11dad031e2bccd9f73cad9ca4 and I got it into the next release I'm working on publishing.
