### ISSUE TITLE
Resgrid.Console.exe dbupate throws unhandled exception

### ISSUE THREAD

**Issue by anewio** [Resgrid/Core#19]
Resgrid.Console.exe dbupate throws unhandled exception:

```
Unhandled exception. System.Configuration.ConfigurationErrorsException: The entry 'ResgridContext' has already been added.
   at System.Configuration.ConfigurationElementCollection.BaseAdd(ConfigurationElement element, Boolean throwIfExists, Boolean ignoreLocks)
   at System.Configuration.ConfigurationElementCollection.BaseAdd(ConfigurationElement element, Boolean throwIfExists)
   at System.Configuration.ConfigurationElementCollection.BaseAdd(ConfigurationElement element)
   at System.Configuration.ConnectionStringSettingsCollection.Add(ConnectionStringSettings settings)
   at Resgrid.Console.Program.SetConnectionString() in C:\ResGrid.Core\Tools\Resgrid.Console\Program.cs:line 87
   at Resgrid.Console.Program.Prime() in C:\ResGrid.Core\Tools\Resgrid.Console\Program.cs:line 42
   at Resgrid.Console.Program.Main(String[] args) in C:\ResGrid.Core\Tools\Resgrid.Console\Program.cs:line 27
```

I believe codes in line #86 and #87 can be removed as "ResgridContext" already exists after line #71 loaded `AppOptions:ConfigPath` successufully.
```
bool configResult = ConfigProcessor.LoadAndProcessConfig(Configuration["AppOptions:ConfigPath"]);
```

Or check the connection key before adding it to `settings` collection as below.

```
if (!configResult)
   settings.Add(new System.Configuration.ConnectionStringSettings("ResgridContext", Configuration["ConnectionStrings:ResgridContext"]));
else
{
   if (settings["ResgridContext"] == null)
   {
	settings.Add(new ConnectionStringSettings("ResgridContext", DataConfig.ConnectionString));
   }
}
```

Please correct me if I misunderstood something.

**Comment by ucswift** [comment]
Hey @anewio thanks for the report!! If you want to deploy and update the db, we use fluent migrator and you can deploy it like this:

dotnet tool install -g FluentMigrator.DotNet.Cli
dotnet fm migrate -p SqlServer -c "[YOUR CONNECTION STRING]" -a "C:\Resgrid\Tools\Resgrid.Providers.Migrations.dll"

I'll look at getting that above error fixed as well.

**Comment by ucswift** [comment]
Ive added your suggested fix and pushed it up. https://github.com/Resgrid/Core/pull/20/files#diff-7d4c97ef391c3330c175ddf7077c0646e3d77994ea8be2c54de0bbc36fb94e1d I'll be working on testing everything out this weekend to try and get the new release pushed out.

**Comment by anewio** [comment]
Thanks @ucswift for the quick response. With the latest commit, `Resgrid.Console.exe dbupate' moves down few steps but ends up with another exception, see attached. 

![image](https://user-images.githubusercontent.com/1287541/107893460-36706f80-6ee0-11eb-990a-7faede4e32d4.png)

Above error message tells `FluentMigrator` was not able to load the embedded migration SQL file: `M0001_InitialMigration.sql` for some reasons. The root cause doesn't seem obvious to me in the first place. After few research, I believe the fix is to add one more function call (see line #66) in the `FluentMigrator` configuration routine at file: `DbUpdateCommand.cs` as below (see line #65 and #66). After the fix,  `Resgrid.Console.exe dbupate' finally works successfully.

![image](https://user-images.githubusercontent.com/1287541/107893767-ded30380-6ee1-11eb-8cda-292f4d79f0b4.png)

**Comment by ucswift** [comment]
@anewio do you get the error if you use the FluentMigrator.DotNet.Cli tool? I've been using that at the moment, but trying to get the Cli working to match documentation. Thanks for that research too, I'll get that added to the code.

**Comment by ucswift** [comment]
I implemented your fix in https://github.com/Resgrid/Core/pull/21.

**Comment by anewio** [comment]
> @anewio do you get the error if you use the FluentMigrator.DotNet.Cli tool? I've been using that at the moment, but trying to get the Cli working to match documentation. Thanks for that research too, I'll get that added to the code.

CLI appears working.
