### ISSUE TITLE
file Resgrid.Web.Services.XML code?

### ISSUE THREAD

**Issue by micheleborello** [Resgrid/Core#3]
I can't find the file
Resgrid.Web.Services.XML
Can anyone help me?
where can i find the code?

**Comment by ucswift** [comment]
Hello,
   Where are you getting that error? It shouldn't be needed as it's just a metadata file created by the build process.

**Comment by micheleborello** [comment]
it should create folders during installation but I can't find them, so the system doesn't react with the APIs.
is it possible to have the complete file? I try to reinstall it

**Comment by ucswift** [comment]
If your looking for the folders, you can download the latest release https://github.com/Resgrid/Core/releases/download/v0.15/ResgridCore_v015.zip and unzip that, that has the directory structure defined. Missing an XML file sounds like a compiler error though, did you run into that somewhere?

**Comment by ucswift** [comment]
Close issue due to inactivity. If the issue is still occurring please open up a new issue and reference this one.
