### ISSUE TITLE
Executing ResgridConsole Docker

### ISSUE THREAD

**Issue by netforce** [Resgrid/Core#30]
In a Linux/Docker-only environment; how to execute the ResgridConsole to e.g. run DbUpdate? I have the feeling it is possible somewhere.. :)

**Comment by ucswift** [comment]
Ohh, thats a good one. So the Resgrid.Console app is .Net Core can run from the Linux command line, but that doesn't help in a Docker only env. Let me see what the options there are.

**Comment by ucswift** [comment]
Hey @netforce sorry for the delay. In https://github.com/Resgrid/Core/commit/1b1faba8848997e112faeb4726702cd5e5187033#diff-4eaa36910ec58948bf0f897dfc9081de17e27f21efa2f0098d249dfcb5adffebR62 I'm adding a env variable "RESGRID_DODBUPGRADE" that will run the database upgrade https://github.com/Resgrid/Core/blob/develop/Workers/Resgrid.Workers.Console/Program.cs#L64 so you can have a worker container with that env set, it'll just run the upgrade and finish. The Scheduled and Events part of the worker won't run, so there isn't a risk of running a container with that variable and it double processing something. I have testing to complete on that to make sure it'll work as intended and if it works ok I'll get it into this next release that I'm starting to prep now.

**Comment by netforce** [comment]
> Ohh, thats a good one. So the Resgrid.Console app is .Net Core can run from the Linux command line, but that doesn't help in a Docker only env. Let me see what the options there are.

you say it is an dotnet app, on the docker container.
So in my mind i could call ResgridConsole <$command> (eg "dotnet Resgrid.Console dbupdate") on the container.. 

`root@docker:# docker-compose exec resgrid.workers.console dotnet Resgrid.Workers.Console dbupdate`

I dont know how the Resgrid.Console.exe is build, if this is a wrapper for the dotnet app? If so, via docker exec you could execute the console app from within the container environment..

**Comment by netforce** [comment]
ok.. after fighting for a while(!) with mssql CLI to creat a user/role/rights/whatever.. (omg wat a complicated mess)... the upgrade failes on an empty database.
It has created the table 'dbo' and nothing more :(


resgrid.workers.console_1   | Finished Initializing Dependencies.
resgrid.workers.console_1   | info: Resgrid.Workers.Console.ScheduledJobsService[0]
resgrid.workers.console_1   |       Starting Database Upgrade
resgrid.workers.console_1   | -------------------------------------------------------------------------------
resgrid.workers.console_1   | VersionMigration migrating
resgrid.workers.console_1   | -------------------------------------------------------------------------------
resgrid.workers.console_1   | Beginning Transaction
resgrid.workers.console_1   | CreateTable VersionInfo
resgrid.workers.console_1   | Committing Transaction
resgrid.workers.console_1   | VersionMigration migrated
resgrid.workers.console_1   | -------------------------------------------------------------------------------
resgrid.workers.console_1   | VersionUniqueMigration migrating
resgrid.workers.console_1   | -------------------------------------------------------------------------------
resgrid.workers.console_1   | Beginning Transaction
resgrid.workers.console_1   | CreateIndex VersionInfo (Version)
resgrid.workers.console_1   | AlterTable VersionInfo
resgrid.workers.console_1   | CreateColumn VersionInfo AppliedOn DateTime
resgrid.workers.console_1   | Committing Transaction
resgrid.workers.console_1   | VersionUniqueMigration migrated
resgrid.workers.console_1   | -------------------------------------------------------------------------------
resgrid.workers.console_1   | VersionDescriptionMigration migrating
resgrid.workers.console_1   | -------------------------------------------------------------------------------
resgrid.workers.console_1   | Beginning Transaction
resgrid.workers.console_1   | AlterTable VersionInfo
resgrid.workers.console_1   | CreateColumn VersionInfo Description String
resgrid.workers.console_1   | Committing Transaction
resgrid.workers.console_1   | VersionDescriptionMigration migrated
resgrid.workers.console_1   | -------------------------------------------------------------------------------
resgrid.workers.console_1   | 1: M0001_InitialMigration migrating
resgrid.workers.console_1   | -------------------------------------------------------------------------------
resgrid.workers.console_1   | Beginning Transaction
resgrid.workers.console_1   | ExecuteEmbeddedSqlScript Resgrid.Providers.Migrations.Sql.M0001_InitialMigration.sql
resgrid.workers.console_1   | Rolling back transaction
resgrid.workers.console_1   | info: Resgrid.Workers.Console.ScheduledJobsService[0]
resgrid.workers.console_1   |       There was an error trying to update the Resgrid Database, see the error output below:
resgrid.workers.console_1   | info: Resgrid.Workers.Console.ScheduledJobsService[0]
resgrid.workers.console_1   |       System.Exception: An error occured executing the following sql:
resgrid.workers.console_1   |       INSERT INTO [dbo].[VersionInfo] ([Version], [AppliedOn], [Description]) VALUES (1, '2021-05-26T15:37:05', N'M0001_InitialMigration')
resgrid.workers.console_1   |       The error was Invalid object name 'dbo.VersionInfo'.
resgrid.workers.console_1   |       
resgrid.workers.console_1   |        ---> System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.VersionInfo'.
resgrid.workers.console_1   |          at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
resgrid.workers.console_1   |          at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
resgrid.workers.console_1   |          at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
resgrid.workers.console_1   |          at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
resgrid.workers.console_1   |          at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
resgrid.workers.console_1   |          at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
resgrid.workers.console_1   |          at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
resgrid.workers.console_1   |          at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.ExecuteNonQuery(String sql)
resgrid.workers.console_1   |       ClientConnectionId:8867ea58-a2e1-40c0-8ba2-86cfa4a7620d
resgrid.workers.console_1   |       Error Number:208,State:1,Class:16
resgrid.workers.console_1   |          --- End of inner exception stack trace ---
resgrid.workers.console_1   |          at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.ExecuteNonQuery(String sql)
resgrid.workers.console_1   |          at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.Process(String sql)
resgrid.workers.console_1   |          at FluentMigrator.Runner.Processors.ProcessorBase.Process(InsertDataExpression expression)
resgrid.workers.console_1   |          at FluentMigrator.Expressions.InsertDataExpression.ExecuteWith(IMigrationProcessor processor)
resgrid.workers.console_1   |          at FluentMigrator.Runner.VersionLoader.UpdateVersionInfo(Int64 version, String description)
resgrid.workers.console_1   |          at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
resgrid.workers.console_1   |          at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
resgrid.workers.console_1   |          at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
resgrid.workers.console_1   |          at FluentMigrator.Runner.MigrationRunner.MigrateUp()
resgrid.workers.console_1   |          at Resgrid.Workers.Console.DatabaseUpgradeService.UpdateDatabase(IServiceProvider serviceProvider) in /src/Workers/Resgrid.Workers.Console/Program.cs:line 375
resgrid.workers.console_1   |          at Resgrid.Workers.Console.DatabaseUpgradeService.ExecuteAsync(CancellationToken stoppingToken) in /src/Workers/Resgrid.Workers.Console/Program.cs:line 352
resgrid.workers.console_1   | info: Microsoft.Hosting.Lifetime[0]
resgrid.workers.console_1   |       Application started. Press Ctrl+C to shut down.
resgrid.workers.console_1   | info: Microsoft.Hosting.Lifetime[0]
resgrid.workers.console_1   |       Hosting environment: Production
resgrid.workers.console_1   | info: Microsoft.Hosting.Lifetime[0]
resgrid.workers.console_1   |       Content root path: /app/

**Comment by ucswift** [comment]
@netforce Yes, it's a .NetCore 3.1 app, I migrated everything from full framework to .NetCore end of last year, so should be able to run like that, the config file access would be the strange one, i.e. making sure it's pointed at the correct database/env. I will be going the env var route to support k8s installations where they might not have solid access to run the container directly. The console project normally used for updating, Resgrid.Console, isn't bundled with the containers itself, but that might be something to look at.

For the database error, that's a strange one, are you able to see any tables created in the database? The scripts are hardcoded to the dbo schema, so that may be another issue, if you have a login that's locked to another schema, like [myUser].[Table] that will cause the error as well.

![image](https://user-images.githubusercontent.com/410646/120004734-f7949000-bf8b-11eb-9a19-cff14ef65c2e.png)

**Comment by netforce** [comment]
clean mssql server, new user, new databases;

The table 'dbo.Templates' does indeed nog exsist in the database 'Resgrid' 
This is al clean install, not an upgrade. Maybe that is the issue?

resgrid.workers.console_1   | -------------------------------------------------------------------------------
resgrid.workers.console_1   | 4: M0004_AddingSortToTemplates migrating
resgrid.workers.console_1   | -------------------------------------------------------------------------------
resgrid.workers.console_1   | Beginning Transaction
resgrid.workers.console_1   | AlterTable Templates
resgrid.workers.console_1   | CreateColumn Templates Sort Int32
resgrid.workers.console_1   | !!! An error occured executing the following sql:
resgrid.workers.console_1   | ALTER TABLE [dbo].[Templates] ADD [Sort] INT
resgrid.workers.console_1   | The error was Cannot find the object "dbo.Templates" because it does not exist or you do not have permissions.
resgrid.workers.console_1   | 
resgrid.workers.console_1   | !!! +- Cannot find the object "dbo.Templates" because it does not exist or you do not have permissions.
resgrid.workers.console_1   | Rolling back transaction
resgrid.workers.console_1   | info: Resgrid.Workers.Console.ScheduledJobsService[0]
resgrid.workers.console_1   |       There was an error trying to update the Resgrid Database, see the error output below:
resgrid.workers.console_1   | info: Resgrid.Workers.Console.ScheduledJobsService[0]
resgrid.workers.console_1   |       System.Exception: An error occured executing the following sql:
resgrid.workers.console_1   |       ALTER TABLE [dbo].[Templates] ADD [Sort] INT
resgrid.workers.console_1   |       The error was Cannot find the object "dbo.Templates" because it does not exist or you do not have permissions.
resgrid.workers.console_1   |       
resgrid.workers.console_1   |        ---> System.Data.SqlClient.SqlException (0x80131904): Cannot find the object "dbo.Templates" because it does not exist or you do not have permissions.
resgrid.workers.console_1   |          at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
resgrid.workers.console_1   |          at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
resgrid.workers.console_1   |          at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
resgrid.workers.console_1   |          at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
resgrid.workers.console_1   |          at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
resgrid.workers.console_1   |          at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
resgrid.workers.console_1   |          at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
resgrid.workers.console_1   |          at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.ExecuteNonQuery(String sql)
resgrid.workers.console_1   |       ClientConnectionId:0aa1d4fc-7e56-4e91-99d1-88a9aa259873
resgrid.workers.console_1   |       Error Number:4902,State:1,Class:16
resgrid.workers.console_1   |          --- End of inner exception stack trace ---
resgrid.workers.console_1   |          at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.ExecuteNonQuery(String sql)
resgrid.workers.console_1   |          at FluentMigrator.Runner.Processors.SqlServer.SqlServerProcessor.Process(String sql)
resgrid.workers.console_1   |          at FluentMigrator.Runner.Processors.ProcessorBase.Process(CreateColumnExpression expression)
resgrid.workers.console_1   |          at FluentMigrator.Expressions.CreateColumnExpression.ExecuteWith(IMigrationProcessor processor)
resgrid.workers.console_1   |          at FluentMigrator.Runner.MigrationRunner.<>c__DisplayClass80_0.<ExecuteExpressions>b__1()
resgrid.workers.console_1   |          at FluentMigrator.Runner.StopWatch.Time(Action action)
resgrid.workers.console_1   |          at FluentMigrator.Runner.MigrationRunner.ExecuteExpressions(ICollection`1 expressions)
resgrid.workers.console_1   |          at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions)
resgrid.workers.console_1   |          at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
resgrid.workers.console_1   |          at FluentMigrator.Runner.MigrationRunner.MigrateUp(Int64 targetVersion, Boolean useAutomaticTransactionManagement)
resgrid.workers.console_1   |          at FluentMigrator.Runner.MigrationRunner.MigrateUp(Boolean useAutomaticTransactionManagement)
resgrid.workers.console_1   |          at FluentMigrator.Runner.MigrationRunner.MigrateUp()
resgrid.workers.console_1   |          at Resgrid.Workers.Console.DatabaseUpgradeService.UpdateDatabase(IServiceProvider serviceProvider) in /src/Workers/Resgrid.Workers.Console/Program.cs:line 375
resgrid.workers.console_1   |          at Resgrid.Workers.Console.DatabaseUpgradeService.ExecuteAsync(CancellationToken stoppingToken) in /src/Workers/Resgrid.Workers.Console/Program.cs:line 352

**Comment by ucswift** [comment]
Let me load this on a fresh test system now and verify, it's possible, templates is newer so that script could be messed up.

**Comment by ucswift** [comment]
@netforce are you pulling from the latest release or source? I just ran the latest release version 0.3.25 and it only goes to Migration 2. I'm wondering if there is a delta with the docker version in that release.

![image](https://user-images.githubusercontent.com/410646/120234896-bf9c7f80-c20d-11eb-9141-9b00d2b8f601.png)

**Comment by netforce** [comment]
it was a "clean" install, not an upgrade. 

I am pulling latest master source from here, no release-tags.
docker-compose build && docker-compose up

* mssql-server 14.0.3381.3-2 on debian Buster.
* Docker version 18.09.1, build 4c52b90

it seems to work fine with no dbo.template table for now.

**Comment by ucswift** [comment]
Ok, I'll test with the latest master, I have no given that a QA pass yet, which I do when I prepare the release, so it easily could be in a weird state. I'll give that a shot today and push up a fix.

**Comment by ucswift** [comment]
@netforce I just pushed https://github.com/Resgrid/Core/commit/0635e0881f1c6341783fcfa6ac12f293d8d6c68b into develop, it fixes the issue, was a typo in the table name. I'll be working on getting that into master here shortly.

**Comment by netforce** [comment]
Seems to be fixed in branch develop indeed :)  I have not tested a clean install yet, because it is to much hassle to create a new database now.

![ScreenShot16062021_110011](https://user-images.githubusercontent.com/1097377/122190452-1e126080-ce92-11eb-814f-5748ecf1e63e.png)
