### ISSUE TITLE
various webroot files not loading

### ISSUE THREAD

**Issue by netforce** [Resgrid/Core#31]
docker env, multiple files cannot be loaded from resgrid.webcore container due to the missing '.map' suffix. 

failed to load SourceMap: Could not load content for http://<snip>/clib/kendo/js/kendo.web.min.js.map: HTTP error: status code 404
failed to load SourceMap: Could not load content for http://<snip>/js/site.min.js.map: HTTP error: status code 404
failed to load SourceMap: Could not load content for http://<snip>/clib/kendo/styles/kendo.common.min.css.map: HTTP error: status code 404,
failed to load SourceMap: Could not load content for http://<snip>/clib/kendo/styles/kendo.material.min.css.map: HTTP error: status code 404,

Files do exsist in container but do not seem to be compiled?
root@20604da8dc2a:/app# ls -l | grep wwwroot
drwxr-xr-x 10 root root     4096 Jun  2 10:19 wwwroot
root@20604da8dc2a:/app#  ls -la wwwroot/clib/kendo/styles/kendo.common.min.css
-rw-r--r-- 1 root root 230490 Jun  1 08:48 wwwroot/clib/kendo/styles/kendo.common.min.css

**Comment by netforce** [comment]
it seems that the kendo-ui library version v2017.2.504 has been undergoing changes since it was loaded into the source of ResgridWeb.

**Comment by ucswift** [comment]
@netforce yea, I've been working on stripping kendo out in terms of standard bootstrap. Hopefully will have that finished in the next release.
