### ISSUE TITLE
HTTP Error 500.19 - Internal Server Error

### ISSUE THREAD

**Issue by dxbro** [Resgrid/Core#38]
I followed the youtube configuration instructions and am getting the following error when opening https://resgrid.local/
![Untitled](https://user-images.githubusercontent.com/88574897/129482499-290d97f4-3e9b-45e6-890e-0d6dd4d23a3a.png)

**Comment by ucswift** [comment]
Hey @dxbro can you look at the Windows Application Log and see if there is an aspnet error in there and supply the details.

**Comment by ucswift** [comment]
Hello,
   We have migrated away for the source based releases with the v0.5.30 release (https://github.com/Resgrid/Core/releases/tag/v0.5.30) and are no longer supporting this release method. Please try and use the new docker based install and if you have any issues you can open up a new issue.
