### ISSUE TITLE
HTTP Error 500.19 - Internal Server Error

### ISSUE THREAD

**Issue by Aaronjacobs678** [Resgrid/Core#4]
Good Morning!

After completing the final step of installation - setting up IIS, when I navigate to the webpage I am getting an internal server error stating the configuration data for the page is invalid. In addition, once the site is setup on IIS and I try to navigate to any internal functions of IIS on its GUI, I keep getting a 'pop-up' with an unknown error. I have attached some screen shots. 

Apologies - quite new to this! :-)

Spec: 
WIN10HOME - 10.0.18363 Build 18363
x64
AMD Ryzen 5 2600 Six-Core Processor, 3400 Mhz, 6 Core(s), 12 Logical Processor(s)
32GB Ram
BIOS Version/Date	American Megatrends Inc. 5220, 12/09/2019
Internet Explorer & Chrome Latest 

Thanks
![error1](https://user-images.githubusercontent.com/61187426/74730009-49088800-523d-11ea-9167-6a60dab069d9.PNG)
![error2](https://user-images.githubusercontent.com/61187426/74730010-49a11e80-523d-11ea-867d-01fe5e7f50e2.PNG)

**Comment by ucswift** [comment]
Hello,
   What do the contents of the Web.config look like at that location C:\Resgrid\Web\Web.config?

**Comment by Aaronjacobs678** [comment]
Evening!

Thanks - as taken from latest zip package:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath=".\Resgrid.WebCore.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
    </system.webServer>
  </location>
</configuration>

**Comment by ucswift** [comment]
That looks like it should be ok, I think the issue is with IIS, do you have .Net 4.6.2 and IIS Features installed for ASP.Net? https://resgrid-core.readthedocs.io/en/latest/installation/index.html#id2 you may also need to make sure the AppPool running the application is setup.

![image](https://user-images.githubusercontent.com/410646/75271615-567bc000-57b1-11ea-947f-858c3aa0c4dc.png)

**Comment by cgabryszek** [comment]
I'm also experiencing this problem. I have verified that I have .Net 4.6.2 and IIS Features installed for ASP.Net installed, as well as the AppPools configured and running as above.

**Comment by ucswift** [comment]
@cgabryszek what OS you running?

**Comment by cgabryszek** [comment]
Server 2019 Standard

**Comment by ucswift** [comment]
kk, lemme spin up the test environments and see if I can repo.

**Comment by Aaronjacobs678** [comment]
Hi All! I ended up changing in Web.cfg, the 'modules="AspNetCoreModuleV2". This allows me to progress past the error, although I have hit the following, 
![error3](https://user-images.githubusercontent.com/61187426/75381687-1ca1db00-58d1-11ea-957d-2735e7abb0cf.PNG)
which I am trying to work out why -

**Comment by Aaronjacobs678** [comment]
Following on from this error - I had to add the following in IIS connection string: "Trusted_Connection=false;" and create a login for "IIS APPPOOL\.NETv4.5" in SQL Database. Again this is all local, so am unsure how it would effect the security. 

I am now up and running at present!

**Comment by ucswift** [comment]
We did change from .Net 4.6.2 to .Net 4.7.2, but I thought that was after the 0.15 release, that could be causing issues. Looking into that right now.

@Aaronjacobs678 Trusted connection would mean the Windows account running the AppPool (it's Identity) would need to be added as a SQL user and granted access to the database. Thats the recommended approach as you don't have username\passwords in the config files. But it's not a huge concern.

**Comment by ucswift** [comment]
Confirmed that the .Net Framework version required is 4.7.2, will be updating the documentation for that.

**Comment by Aaronjacobs678** [comment]
Ucswift - Thank you so much! Great to hear we are going down that route with the trusted connection too. Really appreciate all your input. Excited to be getting stuck in now! :-)

**Comment by ucswift** [comment]
@cgabryszek it's missing from the documentation, I'm adding it now, but your need to install the .Net Core 1.1 IIS Server Hosting Module which you can download from here https://go.microsoft.com/fwlink/?linkid=844461 once it's installed you may need to restart.

**Comment by ucswift** [comment]
As part of our https://github.com/Resgrid/Core/releases/tag/v0.2.21 release we updated the documentation and default credentials for database connection strings and RabbitMQ. Thanks for reporting these issues.

**Comment by ucswift** [comment]
Close issue due to inactivity. If the issue is still occurring please open up a new issue and reference this one.
