### ISSUE TITLE
Error 500 self hosted (Sorry would of posted this in discord but i cant find a link)

### ISSUE THREAD

**Issue by MrDrakeM** [Resgrid/Core#46]
![image](https://user-images.githubusercontent.com/100260841/155270700-16543e78-7d24-4763-b4d3-cfc478214d60.png)
![image](https://user-images.githubusercontent.com/100260841/155271126-41011526-5f1b-4dfd-bb1c-04d882559a17.png)
![image](https://user-images.githubusercontent.com/100260841/155271169-d9128263-db34-4937-bfea-e44ffa75b710.png)
![image](https://user-images.githubusercontent.com/100260841/155271225-46614373-2fdd-4878-b6f9-61beee83b328.png)
![image](https://user-images.githubusercontent.com/100260841/155271244-cac21b58-3c69-4e03-871a-8c5eb5f44cce.png)

![image](https://user-images.githubusercontent.com/100260841/155271350-abcc641e-7f27-4e95-9b18-22114ea85ea5.png)

MS Server 2019
MS Sql 2014
Firefox

**Comment by ucswift** [comment]
Hey @MrDrakeM can you check your Windows Event log in the Application Category, should give you more details on the error from IIS.

Also a new release is next up on my todo list once I get the Unit app update out, it'll be a docker only setup which will ease some of the complication with the current install.

**Comment by ucswift** [comment]
Hello,
   We have migrated away for the source based releases with the v0.5.30 release (https://github.com/Resgrid/Core/releases/tag/v0.5.30) and are no longer supporting this release method. Please try and use the new docker based install and if you have any issues you can open up a new issue.
