### ISSUE TITLE
ResgridAPI Compilation Error

### ISSUE THREAD

**Issue by Aaronjacobs678** [Resgrid/Core#5]
Have readied ResgridAPI, but am suffering this error when heading over to the webpage / help when initially loading the 'resgridapi.local'

Photo attached!

Thanks :-)
![complation](https://user-images.githubusercontent.com/61187426/75388451-f08c5700-58dc-11ea-899d-04d94e4cd064.PNG)

**Comment by ucswift** [comment]
This may be due to missing the .Net Core 1.1 runtime on your system you can download it from here https://dotnet.microsoft.com/download/visual-studio-sdks?utm_source=getdotnetsdk&utm_medium=referral and ensure that you install the correct architecture for your system x64 or x86.

**Comment by ucswift** [comment]
As part of our https://github.com/Resgrid/Core/releases/tag/v0.2.21 release we updated the documentation to point out the missing .Net Core 1.1 runtime dependency. Thank you for reporting this!

**Comment by ucswift** [comment]
Close issue due to inactivity. If the issue is still occurring please open up a new issue and reference this one.
