### ISSUE TITLE
Could not find file 'C:\Resgrid\Api\App_Data\Resgrid.Web.Services.XML'.

### ISSUE THREAD

**Issue by amardimiaty** [Resgrid/Core#6]
Hi I'm Getting this error 

[FileNotFoundException: Could not find file 'C:\Resgrid\Api\App_Data\Resgrid.Web.Services.XML'.]    System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +1404    System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) +1242    System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize) +127    System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy) +122    System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn) +96    System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver) +74    System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData) +0    System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state) +116    System.Xml.XmlTextReaderImpl.OpenUrl() +392    System.Xml.XmlTextReaderImpl.Read() +123    System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace space) +288    System.Xml.XPath.XPathDocument..ctor(String uri, XmlSpace space) +209    Resgrid.Web.Services.Areas.HelpPage.XmlDocumentationProvider..ctor(String documentPath) in C:\TeamCity\buildAgent\work\281f5f08a6efe95a\Web\Resgrid.Services\Areas\HelpPage\XmlDocumentationProvider.cs:35    Resgrid.Web.Services.Areas.HelpPage.HelpPageConfig.Register(HttpConfiguration config) in C:\TeamCity\buildAgent\work\281f5f08a6efe95a\Web\Resgrid.Services\Areas\HelpPage\App_Start\HelpPageConfig.cs:37    System.Web.Mvc.AreaRegistration.RegisterAllAreas(RouteCollection routes, IBuildManager buildManager, Object state) +231    Resgrid.Web.Services.WebApiApplication.Application_Start() in C:\TeamCity\buildAgent\work\281f5f08a6efe95a\Web\Resgrid.Services\Global.asax.cs:74  [HttpException (0x80004005): Could not find file 'C:\Resgrid\Api\App_Data\Resgrid.Web.Services.XML'.]    System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +517    System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +185    System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +168    System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +277    System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +369  [HttpException (0x80004005): Could not find file 'C:\Resgrid\Api\App_Data\Resgrid.Web.Services.XML'.]    System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +532    System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +111    System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +724
--

![image](https://user-images.githubusercontent.com/64644450/81986075-4228c000-9648-11ea-8674-79bc89ddfd76.png)

![image](https://user-images.githubusercontent.com/64644450/81986109-4bb22800-9648-11ea-91dc-045600b38fc4.png)
 
also I want to know how to connect from the mobile app  to local server

**Comment by amardimiaty** [comment]
Hi , I try to do troubleshooting, add the application to visual studio then build it , after building the application I found the xml file and copied to the application , a new error came 

Notice that I'm using .net 4.8

![image](https://user-images.githubusercontent.com/64644450/82007037-42da4a00-967a-11ea-8baa-8113f722e352.png)

**Comment by ucswift** [comment]
Did you download the binaries from the release package zip or directly from source?

**Comment by amardimiaty** [comment]
Hi 
I download it from here 
https://github.com/Resgrid/Core/releases/tag/v0.2.21

**Comment by ucswift** [comment]
Ok, you pulled the ResgridCore_v0.2.21.zip and not the source right? Also what version of Windows are you using?

**Comment by amardimiaty** [comment]
Windows 10

**Comment by amardimiaty** [comment]
Hi ucswift 

I download version 2.20.zip , and deploy I got the site in 
![image](https://user-images.githubusercontent.com/64644450/82107628-606ee880-973a-11ea-9d0b-c66ec94f5676.png)

and API 

![image](https://user-images.githubusercontent.com/64644450/82107648-79779980-973a-11ea-9b0e-9fa6f2a4d4af.png)

I'm very interesting with your software , its very create job

**Comment by ucswift** [comment]
How are your IIS Application Pools configured for both websites in IIS? Can you take screen shots of the basic and advanced screens.

**Comment by amardimiaty** [comment]
Hi please find it below 

![image](https://user-images.githubusercontent.com/64644450/82129225-3b2db900-97d2-11ea-9d7c-9699848add94.png)


![image](https://user-images.githubusercontent.com/64644450/82129235-500a4c80-97d2-11ea-9140-87b43d42386f.png)

![image](https://user-images.githubusercontent.com/64644450/82129246-5d273b80-97d2-11ea-9229-ee0c4ea495c2.png)

![image](https://user-images.githubusercontent.com/64644450/82129252-6ca68480-97d2-11ea-89df-9a14e42b5b75.png)


![image](https://user-images.githubusercontent.com/64644450/82129277-8778f900-97d2-11ea-88c8-21f6eabf6bfc.png)

**Comment by amardimiaty** [comment]
any respond ??

**Comment by ucswift** [comment]
Looks good at a glance, did you install the DotNetCore hosting module as well? https://resgrid-core.readthedocs.io/en/latest/installation/index.html#iis-installation

**Comment by amardimiaty** [comment]
Hi ucswift , thank you for you support , I was able to fix the site issue 
![image](https://user-images.githubusercontent.com/64644450/82238785-e19bca80-9948-11ea-880d-09c8539bdbf7.png)

what I did I connect to physical path via my administrator 

![image](https://user-images.githubusercontent.com/64644450/82238912-0db74b80-9949-11ea-8b15-cbb1e510af5c.png)

but still facing with API 

![image](https://user-images.githubusercontent.com/64644450/82238978-29225680-9949-11ea-926e-84609ee12f16.png)

**Comment by ucswift** [comment]
@amardimiaty Good to hear, the Newtonsoft.Json error went away as well? I'm looking into the Service.xml error and trying to get it spun up in the test environment to validate.

**Comment by amardimiaty** [comment]
Yes Newtonsoft.Json isse is fixed for Resgrid website and it's working fine. Now only error is api error

**Comment by ucswift** [comment]
@amardimiaty looks like it's an issue with the build processes, the xml file is being generated but not published\bundled. I'm working on putting out a release now with that fix. You can download the source and use Visual Studio 2019 to compile it to generate the file locally if you want in the mean time.

**Comment by amardimiaty** [comment]
Ok @ucswift  , Thank you for your support

**Comment by amardimiaty** [comment]
Hi @ucswift  , any update about new release

**Comment by ucswift** [comment]
Hey @amardimiaty I'm going to try and get it out this weekend, had some inflight changes I wanted to include, sorry for the delay.

**Comment by ucswift** [comment]
I release v.2.50 https://github.com/Resgrid/Core/releases/tag/v0.2.50 it should include a fix for the missing xml file.

**Comment by amardimiaty** [comment]
Hi @ucswift  any update

**Comment by ucswift** [comment]
@amardimiaty I posted a couple days ago, release 0.2.50 should have the fix https://github.com/Resgrid/Core/releases/tag/v0.2.50

**Comment by amardimiaty** [comment]
Unfortunately I'm getting the same error on the new release on API 

![image](https://user-images.githubusercontent.com/64644450/83376637-fdd94600-a3e3-11ea-8702-7611d05d55ed.png)

**Comment by ucswift** [comment]
Ok that's a new error, the one that was fixed was the one posted above, missing the Services.xml file, which is now being generated and included. Let me test that release again on a fresh VM.

![image](https://user-images.githubusercontent.com/410646/83377130-7fe85100-a389-11ea-8e4d-da52688852da.png)

**Comment by amardimiaty** [comment]
Ok @ucswift  really thankful

**Comment by ucswift** [comment]
Confirmed the issue, working on a patch release now.

**Comment by ucswift** [comment]
@amardimiaty can you test out https://github.com/Resgrid/Core/releases/tag/v0.2.51 and see if it fixed your issue.

**Comment by amardimiaty** [comment]
Perfect 
![image](https://user-images.githubusercontent.com/64644450/83491863-79f68b00-a4c3-11ea-9578-268351eb48be.png) 


I got issue 
![image](https://user-images.githubusercontent.com/64644450/83491913-8b3f9780-a4c3-11ea-9029-cb6e45979dcc.png)

On the website but I think it is permission issue on my PC

Really Thankful @ucswift

**Comment by ucswift** [comment]
The website runs a slightly diff framework then the api, make sure you got https://go.microsoft.com/fwlink/?linkid=844461 installed, your hostname mapping for resgrid.local is good, the binding for SSL (port 443) is good as the website will only accept HTTPS/SSL traffic. Also make sure the IIS worker process account has rights to read the files from that directly on disk, sometimes, I usually have a "Run As" account setup for that.

**Comment by amardimiaty** [comment]
Perfect @ucswift  

![image](https://user-images.githubusercontent.com/64644450/83610295-47669400-a590-11ea-8161-a53ef4af1e48.png)
