### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by copacarmine** [Resgrid/Core#8]
Hi, first of all congratulations for all the work done. The software is great! 

The error I would like to report to you is that while I'm configuring the product, so I have to make the first login, it says "HTTP Error 500.19 - Internal Server Error" (I enclose screenshots).

Can you tell me why? I followed all the steps and installed it all on a remote vps. 

Thank you in advance and I look forward to your reply.
Carmine 

![errore](https://user-images.githubusercontent.com/59513546/100270994-107aa500-2f59-11eb-99b0-2d889e09fd7a.PNG)

**Comment by copacarmine** [comment]
Aggiornamento:

ho risolto quel problema, però installando la versione, e, accedendo con l'account standard va tutto bene. Però, dall'esterno (app o bigboard) non riesco ad accedere puoi aiutarmi? **I hope you will answer my question as this software is of vital importance to us.**

Poi, se provo a lanciare http://resgridapi.local mi appare questo errore:

Server Error in '/' Application.
Login failed for user 'resgrid_app'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Data.SqlClient.SqlException: Login failed for user 'resgrid_app'.

Source Error:
`
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.`

Stack Trace:
`[SqlException (0x80131904): Login failed for user 'resgrid_app'.]
   System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection) +1338
   System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection) +159
   System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) +382
   System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) +307
   System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry) +198
   System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry) +422
   System.Data.SqlClient.SqlConnection.Open() +199
   System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch(TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed) +104
   System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext) +503
   System.Data.Entity.SqlServer.<>c__DisplayClass33.<UsingConnection>b__32() +560
   System.Data.Entity.SqlServer.<>c__DisplayClass1.<Execute>b__0() +18
   System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Func`1 operation) +234
   System.Data.Entity.SqlServer.SqlProviderServices.UsingMasterConnection(DbConnection sqlConnection, Action`1 act) +909
   System.Data.Entity.SqlServer.SqlProviderServices.CreateDatabaseFromScript(Nullable`1 commandTimeout, DbConnection sqlConnection, String createDatabaseScript) +117
   System.Data.Entity.SqlServer.SqlProviderServices.DbCreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection) +211
   System.Data.Entity.Migrations.Utilities.DatabaseCreator.Create(DbConnection connection) +125
   System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase) +156
   System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration) +116
   System.Data.Entity.Internal.DatabaseCreator.CreateDatabase(InternalContext internalContext, Func`3 createMigrator, ObjectContext objectContext) +124
   System.Data.Entity.Database.Create(DatabaseExistenceState existenceState) +292
   System.Data.Entity.CreateDatabaseIfNotExists`1.InitializeDatabase(TContext context) +187
   System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action) +75
   System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization() +482
   System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input) +177
   System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action) +269
   System.Data.Entity.Internal.InternalContext.ForceOSpaceLoadingForKnownEntityTypes() +60
   System.Data.Entity.DbContext.System.Data.Entity.Infrastructure.IObjectContextAdapter.get_ObjectContext() +31
   Resgrid.Repositories.DataRepository.RepositoryBase`1..ctor(IDbContext context, IISolationLevel isolationLevel) in C:\TeamCity\buildAgent\work\281f5f08a6efe95a\Repositories\Resgrid.Repositories.DataRepository\RepositoryBase.cs:55
   Resgrid.Web.Services.App_Start.AuthTokenMessageHandler..ctor() in C:\TeamCity\buildAgent\work\281f5f08a6efe95a\Web\Resgrid.Services\App_Start\AuthTokenMessageHandler.cs:34
   Resgrid.Web.Services.App_Start.WebApiConfig.Register(HttpConfiguration config) in C:\TeamCity\buildAgent\work\281f5f08a6efe95a\Web\Resgrid.Services\App_Start\WebApiConfig.cs:21
   Resgrid.Web.Services.Startup.Configuration(IAppBuilder app) in C:\TeamCity\buildAgent\work\281f5f08a6efe95a\Web\Resgrid.Services\Startup.cs:59

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +128
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +142
   Owin.Loader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder) +93
   Owin.Loader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder) +212
   Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action`1 startup) +873
   Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build(Action`1 startup) +51
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint() +101
   System.Threading.LazyInitializer.EnsureInitializedCore(T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) +135
   Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context) +160
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +581
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +168
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +277
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +369

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +532
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +111
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +714
`

**Comment by ucswift** [comment]
Hey,
   Looks like your backend database doesn't have a user created for resgrid_app or the password in the config doesn't match the password in the config file. Additionally, you can get that error if the resgrid_app user doesn't have dbo rights for the Resgrid database.

**Comment by copacarmine** [comment]
Okay, I'll check this out immediately. 
So I guess the other problem depends on that too. Right? 
That is that I can't connect from the app or from a web browser

**Comment by ucswift** [comment]
Yea gotta get that sorted out first, it'll cause a number of errors. Once that's set can retry the web and see if the error changes.

**Comment by copacarmine** [comment]
I double-checked the config file and the db and passwords are the same. the user resgrid_app has administrator permissions for the db

**Comment by copacarmine** [comment]
What else can I do?

**Comment by ucswift** [comment]
Is the connection string to the server correct? Is it setup to allow remote TCP connections via port 1433 and there isn't a firewall blocking it?

**Comment by copacarmine** [comment]
Mh don't know. Where can I see it? 
In any case the Windows firewall is deactivated

**Comment by ucswift** [comment]
Same box installation of all the components, i.e. SQL Server and the Web Server are the same box?

**Comment by copacarmine** [comment]
Yes.

A vps with Windows Server 2019. All on the same machine, in C:/ there is the Resgrid folder and then of course everything else. 

In any case, I also have two questions. 

The first one
-You could insert a script/plugin that automatically fills in a "PCR" (Patient Treatment Card). 
The second 
-You could insert a check-list for the vehicles to be carried out at the beginning of the shift (to export then in pdf)

**Comment by ucswift** [comment]
Is your hosts file setup? What server is the SQL server connection string pointing to? You can change it to (local) to pull back to the local instance.

ePCR functionality is on the roadmap, but we have no eta for that functionality yet. It would be used to extend the run reports that are currently in the system.

We are working on rig checklists and maintenance\work log functionality that is something we will be trying to get that functionality in Q1 or Q2 next year.

**Comment by copacarmine** [comment]
The host file is configured correctly (as per the guide). How can I change it to point it locally?

**Comment by ucswift** [comment]
In your ResgridConfig.json file you can add/modify this line https://github.com/Resgrid/Core/blob/v0.2.51/Core/Resgrid.Config/ResgridConfig.json#L4 and change `rgdevserver` to `(local)`

Also, to confirm, you downloaded the zip from the Releases and not the source correct?

**Comment by copacarmine** [comment]
Ok now it works. If I search "http://resgridapi.local" it takes me back to the /help page.
How do I continue to use accounts from apps or bigboards?

**Comment by ucswift** [comment]
So the api should always redirect back to the help (api list page). you should be able to navigate to http://resgrid.local and login using the default credentials to create new accounts.

When those accounts are created uses can connect to your instance. The deployed version of the apps in the stores don't work with private instances yet. As for the bigboard you can deploy your own from here https://github.com/Resgrid/BigBoard.

**Comment by copacarmine** [comment]
Ah ok

So people can only enter by connecting to vps. Right?

Because the most important thing for us is the use of the mobile application. Are there any alternatives?

For BigBoard, can I use the same vps?

**Comment by ucswift** [comment]
I'm working on getting the app store version update with that support in the next version. Note that with the app store version push notifications would not work but all other functionality would. For the big board, yes you would just have to create a new site in IIS just for the big board and give it either a unique port or hostname for clients to connect to.

**Comment by copacarmine** [comment]
Okok.

But one thing is not clear to me, currently wanting to reach my Resgrid installation from the outside is almost impossible. Or am I wrong? So it would be practically unusable for us, unless you find an alternative to the provlrk 

Apps are not open source?

**Comment by ucswift** [comment]
No reason why your installation can't be publicly available, you need to setup publically routable hostnames and IP addresses to hit your installation box. 

The apps being OSS complicates issues, due to private instances of the apps also being deployed to the app stores which can create confusion. Currently we OSS the apps that we don't have deployed to the stores as independent apps, the Dispatch app will most likely be the first we try that path with. If that goes well we hopefully will start moving forward OSS the Unit and Responder app.

**Comment by copacarmine** [comment]
I understand, thank you very much for your answers. We will look for a solution. 

In any case, if I paste the public ip address of the vps on any browser. It redirects me to the "courtesy" page of iis. 

Kindly, could you show me how to do it? And then I would ask you for "personal" advice. Ok for sending the calls via pc from the operations center, but, practically, how could we track the ambulances gps and get the call to them?

Translated with www.DeepL.com/Translator (free version)

**Comment by ucswift** [comment]
So IIS needs to be configured to route for the hostname to the correct IIS app, for example, you would replace resgrid.local with your public web hostname and resgridapi.local with your public api hostname. The .local hostnames are just used for initial standup and don't work over the Internet. Your hosting provider should be able to provide you assistance in that arena, but because it's not directly related to the implementation details of the Resgrid system I cannot provide support in the area.

The Resgrid Unit app would allow you to track vehicles via GPS and dispatch them to calls. Its on the same schedule for getting an update to allow for private instances.

**Comment by copacarmine** [comment]
ok, but there is another error 😶

<img width="1440" alt="Schermata 2020-11-26 alle 09 46 27" src="https://user-images.githubusercontent.com/59513546/100328053-5f155700-2fcc-11eb-9796-41938b18b6ca.png">

**Comment by ucswift** [comment]
Did you get that just navigating to the site, or when you performed an operation? Looks like there may be a missing component.

**Comment by copacarmine** [comment]
This error appears when I try to enter resgrid.local

**Comment by ucswift** [comment]
Can you look in your application event log to see if there are any errors there? Also, can you share your worker process and iis settings for the web instance in iis.

**Comment by ucswift** [comment]
Just wanted to leave a note here, the Resgrid Responder app thats delivered through the store now supports switching the backend api to your own hosted version, 8.201 I believe is that version number. If you can send me the IIS info we can see whats going on with the web error.

**Comment by copacarmine** [comment]
What great news! Tell me what to do and I'll send you all the screens of the apps and various configurations. If it's possible, we'd like to have it all sorted out by Monday so we can activate the app.

**Comment by copacarmine** [comment]
Another question, is there any way (manually of course) to translate or use Italian on web and app?

**Comment by copacarmine** [comment]
Hi! Any news?

**Comment by ucswift** [comment]
Hey,
  Oh sorry was waiting for the output of the application event logs. To determine why the web app was not starting up. Right now the app does not support multiple languages but that is on our roadmap. If you are using Google Chrome you can use the translate plugin to alter the language of the web app.

I can try and quick steps on how to access the event viewer.
![2020-12-21 07_28_55-Window](https://user-images.githubusercontent.com/410646/102793222-755dcb00-435e-11eb-919b-dcec5ebae0b5.png)
![2020-12-21 07_32_18-Window](https://user-images.githubusercontent.com/410646/102793450-c7065580-435e-11eb-8fcd-d8c85c2ed8e4.png)

You are looking for a source that ASP.Net or .Net Core/Framework, or IIS. That is most likely an Warning or Error. You'll have to look through each one and try and find one that a detail that looks like it's dealing with the web app. Should have "Resgrid" somewhere in the text. Copy that entire error body and send it.

**Comment by copacarmine** [comment]
Morning,
next week we are buying a new vps from a new provider, and I will try again with the installation. I will let you know.

In the meantime as a test we are using the version hosted by your site, I've noticed some problems. Among them: 

- in the mobile app in the details of a call there are no contacts (first and last name, phone number etc). 
- There are issues with the gps update.
- In the bigboard there are no sounds with new calls and difficulty updating/connecting. 
- POIs do not appear and cannot be selected as destination. 
- Custom statuses for units do not appear on the mobile app (Resgrid Unit).

**Comment by ucswift** [comment]
@copacarmine thanks for the info, what are the issues with the gps update?

For POIs, that mapping solution is deprecated and were replacing it, so we didn't fully integrate it with the rest of the system. For the unit custom statuses, did you tie the custom status with the unit type and that type is applied to the unit? I am working on a Responder and BigBoard app update here shortly and will take a look at those 2 issues.

If your looking at a new VPS, I might recommend going the Container route instead of the code install route if you have expertise in that, I'm working on getting that done with this release.

**Comment by copacarmine** [comment]
I know it's not related to the issue. More like I'd like some advice. 
What do you recommend for ambulances/operators? Tablets or similar?

Since we would like something accurate and reliable (especially with gps). I did some testing with a Samsung tablet and the Resgrid Unit app but the gps on the bigboard would stay stationary in the middle and update with static locations that when I updated the various statuses

**Comment by ucswift** [comment]
The Bigboard map only updates when there is status updates calls, that prevents excessive drawing of the map. We are looking at some way to display the live geolocation data in a form that would not prevent map redraws. Currently the live location data is stored in the db, but not displayed unless a refresh occurs.

I would recommend tablets, with a tough case and a keyboard in the case. If your expecting PCR's to be completed on the device in the rig that would allow it to be pulled off and used in the passenger set or in the box to complete the PCR. The keyboard there helps out a lot for the reports. If you need a laptop equiv, I would recommend the non-ARM Microsoft Surface devices, they are basically tablets, support full Windows and you can have tough cases and keyboard with them. I would not recommend non-attached Bluetooth keyboard (they have to be connected to the tablet or the case, as they can become projectiles in an accident, and tend to slide around and cause issues if left laying about.

**Comment by copacarmine** [comment]
OK I get it.
Yes, because what we would need is just a map that updates almost "in real time". For organizational issues. 
I look forward to this update.

**Comment by copacarmine** [comment]
Hi, we got the new vps and I am proceeding with the installation. I am proceeding with the guide you made, but there is already the "first hiccup", and it is the installation of rabbitmq. There is no way to make it work, I tried all the methods, all the options and guides from the internet, but nothing, it doesn't work. Are there any alternatives?

**Comment by ucswift** [comment]
What are the issues you are having with RabbitMQ?

**Comment by copacarmine** [comment]
**Just installed, when I try to start it it gives me this error. And in no way I can solve it and continue with the work.**



C:\Program Files\RabbitMQ Server\rabbitmq_server-3.8.9\sbin>rabbitmqctl start_app
Starting node rabbit@vmi510578 ...
Error: unable to perform an operation on node 'rabbit@vmi510578'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node rabbit@vmi510578
 * If target node is configured to use long node names, don't forget to use --longnames with CLI tools

DIAGNOSTICS
===========

attempted to contact: [rabbit@vmi510578]

rabbit@vmi510578:
  * connected to epmd (port 4369) on vmi510578
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on vmi510578
  * suggestion: start the node

Current node details:
 * node name: 'rabbitmqcli-5620-rabbit@vmi510578'
 * effective user's home directory: C:\Users\Administrator
 * Erlang cookie hash: srib0l6KG9E+G9ZP38MV/Q==

**Comment by ucswift** [comment]
Looks like the node isn't running. Have you started it?

**Comment by copacarmine** [comment]
Yes, but

Configuring logger redirection
18:58:34.736 [warning] Using RABBITMQ_ADVANCED_CONFIG_FILE: c:/Users/Administrator/AppData/Roaming/RabbitMQ/advanced.config

BOOT FAILED
18:58:37.831 [error]
===========
18:58:37.831 [error] BOOT FAILED
ERROR: distribution port 25672 in use by another node: rabbit@vmi510578
18:58:37.831 [error] ===========

18:58:37.831 [error] ERROR: distribution port 25672 in use by another node: rabbit@vmi510578
18:58:37.831 [error]
18:58:38.841 [error] Supervisor rabbit_prelaunch_sup had child prelaunch started with rabbit_prelaunch:run_prelaunch_first_phase() at undefined exit with reason {dist_port_already_used,25672,"rabbit","vmi510578"} in context start_error
18:58:38.849 [error] CRASH REPORT Process <0.155.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,prelaunch,{dist_port_already_used,25672,"rabbit","vmi510578"}}},{rabbit_prelaunch_app,start,[normal,[]]}} in application_master:init/4 line 138
{"Kernel pid terminated",application_controller,"{application_start_failure,rabbitmq_prelaunch,{{shutdown,{failed_to_start_child,prelaunch,{dist_port_already_used,25672,\"rabbit\",\"vmi510578\"}}},{rabbit_prelaunch_app,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,rabbitmq_prelaunch,{{shutdown,{failed_to_start_child,prelaunch,{dist_port_already_used,25672,"rabbit","vmi510578"}}},{rabbit_

Crash dump is being written to: erl_crash.dump...done

C:\Program Files\RabbitMQ Server\rabbitmq_server-3.8.9\sbin>

**Comment by ucswift** [comment]
Hmm, is something else running or locking port 25672? The context that Rabbit is running under will need to be able to open up those ports so there could be something blocking that. You could run a `netstat` to see if something else is using that port locally.

For running on a VPS, those ports will need to be open locally, but I would not expose them to the Internet. Your VPS should have a firewall in front of the VPS where you only allow some traffic through (RDP, HTTP, HTTPS).

**Comment by copacarmine** [comment]
I ran netstat but nothing seems to be there. If you want I paste the results

**Comment by ucswift** [comment]
If there are no open ports for 25672, then my guess is it's being blocked from opening that port in the system. Could be an issue where UAC is enabled and you need to run as administrator the cmd for it to work correctly. You could also get the Windows Service running for it, that should also have rights to open up a port.

**Comment by copacarmine** [comment]
This is the cmd used by administrator 


C:\Program Files\RabbitMQ Server\rabbitmq_server-3.8.9\sbin>rabbitmqctl start_app
Starting node rabbit@vmi510578 ...

C:\Program Files\RabbitMQ Server\rabbitmq_server-3.8.9\sbin>rabbitmqctl add_user regrid resgrid!
Error: this command requires the 'rabbit' app to be running on the target node. Start it with 'rabbitmqctl start_app'.
Arguments given:
        add_user regrid resgrid!

[1mUsage[0m

rabbitmqctl [--node <node>] [--longnames] [--quiet] add_user <username> <password>

C:\Program Files\RabbitMQ Server\rabbitmq_server-3.8.9\sbin>rabbitmqctl start_app
Starting node rabbit@vmi510578 ...
Error: unable to perform an operation on node 'rabbit@vmi510578'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node rabbit@vmi510578
 * If target node is configured to use long node names, don't forget to use --longnames with CLI tools

DIAGNOSTICS
===========

attempted to contact: [rabbit@vmi510578]

rabbit@vmi510578:
  * connected to epmd (port 4369) on vmi510578
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on vmi510578
  * suggestion: start the node

Current node details:
 * node name: 'rabbitmqcli-4948-rabbit@vmi510578'
 * effective user's home directory: C:\Users\Administrator
 * Erlang cookie hash: srib0l6KG9E+G9ZP38MV/Q==


C:\Program Files\RabbitMQ Server\rabbitmq_server-3.8.9\sbin>

**Comment by ucswift** [comment]
Can you launch 2 cmd apps, run one as admin and use start_app there, then the 2nd window run the add user command. I would recommend getting the Windows service for Rabbit running so it's started automatically https://www.rabbitmq.com/install-windows.html#service

**Comment by copacarmine** [comment]
Even starting it as a service doesn't change anything. I really don't know what to do

**Comment by ucswift** [comment]
Is the windows service running? Whats the output in the logs folder or event viewer?

**Comment by ucswift** [comment]
in the sbin directory if you run `rabbitmqctl status` whats the output (if the windows service is running)

**Comment by copacarmine** [comment]
C:\Program Files\RabbitMQ Server\rabbitmq_server-3.8.9\sbin>rabbitmqctl status
Error: this command requires the 'rabbit' app to be running on the target node. Start it with 'rabbitmqctl start_app'.
Arguments given:
        status

[1mUsage[0m

rabbitmqctl [--node <node>] [--longnames] [--quiet] status [--unit <unit>] [--timeout <timeout>]

**Comment by copacarmine** [comment]
**Hi! All solved with RabbitMQ. At the point of doing the database update I get this error. Suggestions?**



Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>cd C:\Resgrid\Tools\

C:\Resgrid\Tools>Resgrid.Console.exe dbupdate
Resgrid Console
-----------------------------------------
Loaded Config: C:\Resgrid\Config\ResgridConfig.json

Unhandled Exception: Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = OutboundEventProvider (ReflectionActivator), Services = [Resgrid.Model.Providers.IOutboundEventProvider], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = OutboundQueueProvider (ReflectionActivator), Services = [Resgrid.Model.Providers.IOutboundQueueProvider], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor()' on type 'OutboundQueueProvider'. ---> Could not load file or assembly 'Resgrid.Providers.Bus.Rabbit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = OutboundQueueProvider (ReflectionActivator), Services = [Resgrid.Model.Providers.IOutboundQueueProvider], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor()' on type 'OutboundQueueProvider'. ---> Could not load file or assembly 'Resgrid.Providers.Bus.Rabbit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor()' on type 'OutboundQueueProvider'. ---> Could not load file or assembly 'Resgrid.Providers.Bus.Rabbit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. (See inner exception for details.) ---> System.IO.FileNotFoundException: Could not load file or assembly 'Resgrid.Providers.Bus.Rabbit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at Resgrid.Providers.Bus.OutboundQueueProvider..ctor()
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__5_0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass0_0.<CanSupplyValue>b__0()
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__5_0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Resgrid.Console.Program.Prime() in C:\TeamCity\buildAgent\work\281f5f08a6efe95a\Tools\Resgrid.Console\Program.cs:line 47
   at Resgrid.Console.Program.Main(String[] args) in C:\TeamCity\buildAgent\work\281f5f08a6efe95a\Tools\Resgrid.Console\Program.cs:line 24

**Comment by copacarmine** [comment]
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>cd C:\Resgrid\Tools

C:\Resgrid\Tools>Resgrid.Console.exe dbupdate
Resgrid Console
-----------------------------------------
Loaded Config: C:\Resgrid\Config\ResgridConfig.json
Starting the Resgrid Database Update Process

Unhandled Exception: System.ArgumentException: Keyword not supported: '(local)\sqlserverd;database'.
   at Consolas.Core.CommandExecutable.TryInvokeCommand(CommandSet command, MethodInfo methodInfo)
   at Consolas.Core.CommandExecutable.ExecuteCommand(Type commandType, CommandSet command)
   at Consolas.Core.CommandExecutable.Execute()
   at Consolas.Core.ConsoleApp`1.Match(String[] args)
   at Resgrid.Console.Program.Main(String[] args) in C:\TeamCity\buildAgent\work\281f5f08a6efe95a\Tools\Resgrid.Console\Program.cs:line 26

C:\Resgrid\Tools>

**Comment by copacarmine** [comment]
Okay, all resolved. Installed everything. In local I enter correctly on regrid, but not on resgridapi.local (error in picture 1).

Then trying to connect from my pc to resgrid I get this (picture 2)


*IMAGE 1*
![eRROR509](https://user-images.githubusercontent.com/59513546/105758227-50590b00-5f4f-11eb-9068-12e2db410862.PNG)


*IMAGE 2*
![404notfound](https://user-images.githubusercontent.com/59513546/105758220-4cc58400-5f4f-11eb-9df9-d999e7238756.PNG)

**Comment by ucswift** [comment]
Worked with user over Discord to resolve installation issue. Closing this issue as it's been resolved.
